vuejs/language-tools

packages/vscode-vue-languageservice/src/services/completion.ts

This is useful and common for those attributes can accept static string as values.

feat: support complete attribute without v-bind

---

package.json

Closes #107 
@odex21 There may be a bug from the "Debugger for Firefox" VS Code extension, and adding breakpoints may not have effects, so you may need "Debugger for Chrome" VS Code extension and use Chrome to debug your code.

feat: support adding breakpoints (close #107)

---

packages/shared/src/requests.ts
packages/vscode-client/src/features/tagNameCase.ts
packages/vscode-server/src/features/lspFeatures.ts

I found a typo, fixed it.
**typo**:
```
volar$ rg "GetClientTarNameCaseRequest" packages
packages/shared/src/requests.ts
55:export namespace GetClientTarNameCaseRequest {
packages/vscode-server/src/features/lspFeatures.ts
21:					tag: () => connection.sendRequest(shared.GetClientTarNameCaseRequest.type, {
packages/vscode-client/src/features/tagNameCase.ts
14:	languageClient.onRequest(shared.GetClientTarNameCaseRequest.type, async handler => {
```

fix: typo, TarNameCase -> TagNameCase

---

packages/server/src/serviceHandler.ts
packages/shared/src/ts.ts
packages/vscode-vue-languageservice/src/generators/template.ts
packages/vscode-vue-languageservice/src/generators/template_scriptSetup.ts
packages/vscode-vue-languageservice/src/languageService.ts
packages/vscode-vue-languageservice/src/services/diagnostics.ts
packages/vscode-vue-languageservice/src/sourceFile.ts
packages/vscode-vue-languageservice/src/types.ts
packages/vscode-vue-languageservice/src/use/useSfcScriptGen.ts
packages/vscode-vue-languageservice/src/use/useSfcTemplateCompileResult.ts
packages/vscode-vue-languageservice/src/use/useSfcTemplateScript.ts
packages/vscode-vue-languageservice/src/utils/vue2TemplateCompiler.ts

Close #346
Support Vue 2 template by `experimentalCompatMode` option (may change in future):
```jsonc
// tsconfig.json
{
"compilerOptions": {
...
},
"experimentalCompatMode": 2
},
}
```

Support for Vue 2 template

---

packages/vscode-vue-languageservice/src/commands/pugToHtml.ts

I was curious about the position of the </template> tag in Code Lens' pug-to-html. (Of course, this is not a problem since you can use the formatting feature to fix it)
Adjusted by adding line breaks.
**volar version:** 
v0.26.15
https://user-images.githubusercontent.com/188642/129130092-b62b06af-2769-4230-9b13-d94cb6d73101.mp4
https://user-images.githubusercontent.com/188642/129130108-1c8101c1-ea18-427c-991a-97d756da5c2d.mp4
Of course, if there are any problems, you can close this Pull Request without Merge. 🙇

fix: Adjusting the position of "</template>" tags in CodeLens' "pug-to-html"

---

packages/vscode-vue-languageservice/src/commands/useSetupSugar.ts

Adjusted the code block insertion order generated by useSetupSugar. Now the block like `<script setup>` is below the `<script>`

fix: useSetupSugar blocks order error (#378)

---

packages/shared/src/vue.ts
packages/vscode-vue-languageservice/src/sourceFile.ts

Could you add an offset for `end: number` to the SfcBlock interface?
I would like to use "shared.SfcBlock" etc. in coc-volar's `volar.action.splitEditor`, but I would also like an offset for "end".

chore: Add "end" offset to shared.SfcBlock

---

packages/vscode-typescript-languageservice/src/services/diagnostics.ts

In TypeScript or JavaScript file
Volar

fix: incorrect logic of `translateDiagnosticRelated`

---

packages/vscode-vue-languageservice/src/generators/template.ts
packages/vscode-vue-languageservice/src/utils/globalDoc.ts

See: https://github.com/johnsoncodehk/volar/issues/539#issuecomment-930229898

fix: Pick up the correct slot scope type from `$slots`

---

packages/vscode-vue-languageservice/src/generators/template.ts
packages/vscode-vue-languageservice/src/utils/globalDoc.ts
packages/vscode-vue-languageservice/testCases/tsconfig.json
packages/vscode-vue-languageservice/testCases/typeChecks/v_for.vue
packages/vscode-vue-languageservice/tests/index.spec.ts
packages/vscode-vue-languageservice/tests/typeChecks/v_for.ts

Improved some types and added some tests.
---
Now v-for is transformed into the code below.
```ts
// when noUncheckedIndexedAccess: true
declare const record: Record<string, string>
declare function __VLS_getVforSourceType<T>(source: T): T extends number ? number[] : T;
declare function __VLS_getVforKeyType<T>(source: T): typeof Symbol.iterator extends keyof T ? number : keyof T;
declare function __VLS_getVforIndexType<T>(source: T): typeof Symbol.iterator extends keyof T ? undefined : number;
declare function __VLS_pickForItem<S, T2>(source: S, forInItem: T2): S extends { [Symbol.iterator](): IterableIterator<infer T1> } ? T1 : T2;
const __VLS_11 = __VLS_getVforSourceType(record) // Record<string, string>
for (const __VLS_12 in __VLS_11) {
const val = __VLS_pickForItem(__VLS_11, …
```

Improve v-for type

---

packages/vscode-vue-languageservice/src/sourceFile.ts

This fixes the issue where the SFC template is not Pug or HTML: `vscode-vue-languageservice` incorrectly assumes that the SFC template has `HTML` lang.

VSCode Vue Language Service: Check the template lang before assuming sourceLang is 'html'

---

packages/server/src/configs.ts
packages/vscode-vue-languageservice/src/services/hover.ts

When trying to use `@volar/server` in non-VSCode clients (in my case, Emacs' [eglot](https://github.com/joaotavora/eglot)), hovering over a HTML tag in the `<template>` section causes the server to error with `TypeError: Cannot read property 'documentation' of null`. The reason for this is that `connection.workspace.getConfiguration` returns `null` when the client doesn't have a response for the given section in `workspace/configuration`, and so [getHtmlHoverSettings](https://github.com/johnsoncodehk/volar/blob/eb2d8e4f40c3e8a2df5e855bc298ccafbe721f05/packages/server/src/configs.ts#L39) returns `null` when `htmlLs.doHover` used [here](https://github.com/johnsoncodehk/volar/blob/master/packages/vscode-vue-languageservice/src/services/hover.ts#L107) expects `undefined` or an object.
Since …

Fix TypeError that can occur in non-VSCode clients

---

extensions/vscode-vue-language-features/README.md

I thought it was necessary to add this comment to let the user know how automatic formatting of `style` works.
If you don't think it's necessary, just close the PR. Thanks~

docs: add auto formatting of style note

---

README.md

Since version 1.0.8 LSP-volar supports starting in `*.ts | *.tsx | *.js | *.jsx` files.

LSP-volar now supports starting in non-vue files

---

README.md

docs: how to prevent issues related to `@types/react`

---

packages/shared/package.json
packages/vue-tsc/bin/vue-tsc.js

**What's the problem this PR addresses?**
- `@volar/shared` depends on `vscode-html-languageservice` but doesn't declare it as a dependency.
- The patch that `vue-tsc` applies to `tsc` doesn't pre-resolve the path to the proxy which makes it rely on hoisting to place `typescript` and `vue-tsc` next to each other which isn't guaranteed to happen.
**How did you fix it?**
- Move `vscode-html-languageservice` from `devDependencies` to `dependencies`.
- Inject the absolute path to the proxy instead of an identifier.

fix: resolve dependency issues

---

extensions/vscode-vue-language-features/package.json

It seems that `vue-jsconfig.schema.json` does not exist in the schemas directory. When editing `jsconfig.json`, the json language server will output an error.
Changed `jsconfig.json` related "jsonValidation" to `vue-tsconfig.schema.json`.

fix(schemas): missing "vue-jsconfig.schema.json"

---

extensions/vscode-vue-language-features/README.md

Hi, I'd like to propose a tiny addition to the docs if you're accepting.
I think this would be helpful to folks migrating over to Volar from Vetur who, like myself, don't really care about customizing their snippets, but just want some quick, ready-made snippets they can install with a click. Sarah Drasner's snippets are relatively popular, with Vue 3 support, and she's a member of Vue's core team so I suspect they will be well maintained. I read through #183 and #781 and appreciate the rationale not to include built-in snippets, but this seems like an easy alternative.
Happy to amend or close if you're not accepting PR's of this sort. Thanks!

docs: suggest snippets from the VSCode Marketplace

---

packages/shared/src/ts.ts
packages/vue-language-service/src/languageService.ts

fix #1043 
This PR replaces `console.log` to `console.warn` where their output affects to LSP clients.

fix: use `console.warn` instead of `console.log`

---

packages/vue-code-gen/src/generators/template.ts

Added missing support for attribute binding syntax `:<name>.attr`.  Reference https://vuejs.org/api/built-in-directives.html#v-bind
For example
```
<div :someProperty.attr="someString"></div>
```
related to #992 
The other way of binding attribute
```
<div ^someProperty="someString"></div>
```
I don't know how to fix yet. When debugging, `prop.type` for this syntax is `CompilerDOM.NodeTypes.ATTRIBUTE` while the above syntax is `CompilerDOM.NodeTypes.DIRECTIVE`. Not sure if that is Vue SFC compiler issue or not. 
IMO, since both syntaxes are equivalent, their `prop.type` should be the same. Probably you have more insight with Vue team about that.
- Pick up any projects using `vue-tsc`
- Create a SFC file with attribute binding syntax `:<name>.attr` in HTML part
- Run `vue-tsc` against that …

fix(code-gen): support attribute binding syntax `:<name>.attr`

---

extensions/vscode-vue-language-features/bin/vite.js
packages/experimental/src/client.ts
packages/pug-language-service/src/baseParse.ts
packages/shared/src/common.ts
packages/typescript-language-service/src/index.ts
packages/typescript-language-service/src/utils/previewer.ts
packages/vue-code-gen/src/generators/template.ts
packages/vue-code-gen/src/parsers/cssBindRanges.ts
packages/vue-language-server/src/project.ts
packages/vue-language-service/src/commonPlugins/pugBeautify.ts
packages/vue-language-service/src/vuePlugins/vueTemplateLanguage.ts
packages/vue-typescript/src/use/useSfcTemplateScript.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

chore: replace deprecated String.prototype.substr()

---

extensions/vscode-vue-language-features/package.json

`volar.formatting.printWidth` settings have been removed as they are no longer needed. <https://github.com/johnsoncodehk/volar/commit/54bd09578f6f8adf95d5dd587d395a1f8b858d60>

remove "volar.formatting.printWidth" setting

---

extensions/vscode-vue-language-features/schemas/vue-tsconfig.schema.json
packages/vue-code-gen/src/generators/script.ts
packages/vue-code-gen/src/index.ts
packages/vue-typescript/src/types.ts
packages/vue-typescript/src/use/useSfcScriptGen.ts
packages/vue-typescript/src/vueFile.ts

close #1190
Usage:
```
tsconfig.json / jsconfig.json
{
"experimentalShamefullySupportOptionsApi": true
},
}
```

feat: add option `experimentalShamefullySupportOptionsApi`

---

extensions/vscode-vue-language-features/package.json
extensions/vscode-vue-language-features/src/common.ts
extensions/vscode-vue-language-features/src/nodeClientMain.ts

It's a workaround to solved `JavaScript heap out of memory`
I have problem on `JavaScript heap out of memory`. I found many related issues but many of them closed by lack of info to repro
- https://github.com/johnsoncodehk/volar/issues/862
- https://github.com/johnsoncodehk/volar/issues/658#issuecomment-1014084522
- https://github.com/johnsoncodehk/volar/issues/1242#issuecomment-1114579455
- https://github.com/johnsoncodehk/volar/issues/514
- https://github.com/johnsoncodehk/volar/issues/1025
- https://github.com/johnsoncodehk/volar/issues/1106
```sh
$ echo "In my case"
$ NODE_OPTIONS='--max_old_space_size=700' npx vue-tsc --noEmit 
<--- Last few GCs --->
[12514:0x56b6af0]    26053 ms: Mark-sweep (reduce) 698.3 (711.3) -> 697.3 (711.1) MB, 220.5 / 0.0 ms  (average mu = 0.167, current mu = …
```

add option to set `--max-old-space-size` on server

---

extensions/vscode-vue-language-features/src/features/doctor.ts

Check tsconfig for "expermentalCompatMode".
Also format infos into markdown list.
This fixes third point of https://github.com/johnsoncodehk/volar/issues/1254.

Show experimentalCompatMode Info

---

extensions/vscode-vue-language-features/package.json

Vite doesn't really print build errors to the terminal AFAIK, this is for the background patterns that will allow to properly set a vite task as `isBackground`, and to properly use it in `preLaunchTask` in launch configurations.

Add a Vite problem matcher to the VS Code extension

---

extensions/vscode-vue-language-features/scripts/build-node.js

Because the path split sign under window is `\` so there will be a bug when use windows to build
Can not replace `/umd/` to `/esm/` in windows

fix: fix build error in windows

---

packages/vue-typescript/src/typescriptRuntime.ts
packages/vue-typescript/src/utils/moduleSpecifierCache.ts
packages/vue-typescript/src/utils/packageJsonCache.ts
packages/vue-typescript/src/utils/ts.ts
pnpm-lock.yaml

feat: update auto-import cache logic for TS 4.7

---

packages/vue-typescript/src/utils/ts.ts

Similar to #1046, `console.warn()` should be used here, since `console.log()` sends output to stdio and it may break some LSP clients which use stdio to communicate with LSP servers (e.g., vim-lsp).

fix: use console.warn instead of console.log

---

extensions/vscode-vue-language-features/src/features/fileReferences.ts

Error when executed directly from command.
https://user-images.githubusercontent.com/188642/172530126-2fb270ca-d88a-48c0-a9ad-f92088ed676e.mp4

fix: direct execution of vue.findAllFileReferences command

---

README.md
packages/vue-typescript/src/utils/parseCssClassNames.ts

Closes #1481  
Fixes an issue when parsing css classes when css contains "." character that are not class selectors (example `1.5em` or when using scss modules syntax).

fix: css classes parsing

---

extensions/vscode-vue-language-features/package.json
extensions/vscode-vue-language-features/src/features/doctor.ts
pnpm-lock.yaml

Check "target" und "@vue/runtime-dom" options when opening doctor panel
https://github.com/johnsoncodehk/volar/issues/1254

Doctor panel features

---

.vscode/settings.json

Follow up of https://github.com/johnsoncodehk/volar/issues/1512
Only adding "editor.defaultFormatter" in vscode settings didn't work  for me. My VSCode was still using prettier.
When adding "editor.defaultFormatter" with specific languages it works.

extend editor.defaultFormatter

---

extensions/vscode-vue-language-features/package.json

This PR aims to fix the type of `volar.takeOverMode.enabled` when its sets to `auto`.

Fix takeOverMode auto type

---

docs/installation.md
packages/vue-typescript/src/sourceFile.ts

The old logic `(compilerOptions.jsx ?? ts.JsxEmit.Preserve) !== ts.JsxEmit.Preserve` didn't seem right in case the `compilerOptions.jsx` was not set as then it assumed that the default value is `preserve` and thus that the resolved value is also `preserve`. That would result in no diagnostic from https://github.com/johnsoncodehk/volar/blob/a77cc83c9f6ac0ff4fdab9989fa9eceadc844a86/packages/vue-language-service/src/plugins/vue.ts#L152-L165 being created.
Maybe this had to do with a change in 4e6f6f77c589e39c1139a323fa75a7633eceadc4 where the real, evaluated options were checked? Not sure.

fix: wrong check for whether jsx option is set

---

extensions/vscode-vue-language-features/schemas/vue-tsconfig.schema.json

According to the code the default value of `experimentalImplicitWrapComponentOptionsWithVue2Extend` is `onlyJs`:
https://github.com/johnsoncodehk/volar/blob/834a8668bb75e7ce9f5da4b3ea8c9200d60ee04a/packages/vue-typescript/src/plugins/vue-typescript-scripts.ts#L36-L36

fix: update default value in schema

---

extensions/vscode-vue-language-features/src/features/tsVersion.ts

feat: support for "JavaScript and TypeScript Nightly"

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/reference-type-exposed/component.vue

When a component uses `expose` or `defineExpose()` on its methods or data, it needs to be documented.
This PR adds documentation for the method.

feat(vue-component-meta): extract the "exposed" metadata

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/ts-component/PropDefinitions.ts
packages/vue-test-workspace/vue-component-meta/ts-component/component.ts
packages/vue-test-workspace/vue-component-meta/ts-named-export/component.ts

If you are library author and have a lot of components to maintain, using ts files is often simpler.
Check out bootstrap-vue or vuetify and see for yourself.
This allows for parsing components like:
```ts
export default defineComponent({
setup(props: MyProps){
return () => {
h('pre', JSON.stringify(props, null, 2));
}
}
})
```
or even 
```tsx
export const MyFunctionalComponent = defineComponent((props: MyProps) => {
<pre>{ JSON.stringify(props, null, 2) } </pre> 
})

feat(component-meta): allow documenting components in .ts files

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/reference-type-props/component.vue

Using `withDefault()` or the `props` option in the options API, we can define default values for props.
These are useful to extract from the code.

feat(vue-component-meta): add prop default values to documentation

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/src/types.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/options-api/component.ts
packages/vue-test-workspace/vue-component-meta/reference-type-props/component.vue
packages/vue-test-workspace/vue-component-meta/reference-type-props/my-props.ts

In case the type of a prop is an `array` or an `object`, the default has to be passed as a function.
The function is there to avoid referencing the same default object on every instance of the component. It does not bring any semantic information to the user of a component.
Additionally, this PR is meant to add support for default values for props defined using the options API.

feat: add default detection for complex types

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/reference-type-props/my-props.ts

This fix `maximum stack size exceeded` when props use recursive types like:
```ts
export interface MyNestedRecursiveProps {
recursive: MyNestedRecursiveProps
}
defineProps<{
myProp: MyNestedRecursiveProps
}>()
```

[vue-component-meta] fix: recursive schema parsing

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/reference-type-props/component-js-setup.vue

This allows to parse `defineProps` in `<script setup>`
```vue
<script setup>
defineProps({
/**
* Required foo property
*/
foo: {
type: String,
required: true,
},
/**
* The hello property.
*
* @since v1.0.0
*/
hello: {
type: String,
default: 'Hello'
},
numberOrStringProp: {
type: [Number, String],
default: 42
},
arrayProps: {
type: Array,
default: () => [42, 43, 44]
}
})
</script>
```
chore:
- use same checker instance in tests (may we want to enable `schema` and `printer` by default?)

[vue-component-meta] fix: parse defineProps in script setup with option

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/src/types.ts

Expose more variables: `typeChecker`, `rawType`...

feat(vue-component-meta): expose more infos

---

packages/alpine-language-core/src/index.ts
packages/alpine-language-core/src/plugins/file-html.ts
packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/lsContext.ts
packages/vue-language-core/src/plugins/empty.ts
packages/vue-language-core/src/plugins/file-html.ts
packages/vue-language-core/src/plugins/file-md.ts
packages/vue-language-core/src/plugins/file-vue.ts
packages/vue-language-core/src/plugins/vue-sfc-customblocks.ts
packages/vue-language-core/src/plugins/vue-sfc-scripts.ts
packages/vue-language-core/src/plugins/vue-sfc-styles.ts
packages/vue-language-core/src/plugins/vue-sfc-template.ts
packages/vue-language-core/src/plugins/vue-template-html.ts
packages/vue-language-core/src/plugins/vue-template-pug.ts
packages/vue-language-core/src/plugins/vue-tsx.ts
packages/vue-language-core/src/sourceFile.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/ts.ts
packages/vue-language-service/src/documentService.ts

Closes #185
Please note that the API interface is not stable, it may change before v1.0.
- `tsconfig.json`
```jsoncc
{
"plugins": ["./your-plugin"]
}
}
```
Example: https://github.com/johnsoncodehk/volar-starter/blob/master/vue-i18n.js

feat: Support for Plugin API

---

packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/reference-type-props/component-js-setup.vue
packages/vue-test-workspace/vue-component-meta/reference-type-props/component-js.vue
packages/vue-test-workspace/vue-component-meta/reference-type-props/my-props.ts

Extra tests to verify the behavior noticed in issue [(#1695) ](https://github.com/johnsoncodehk/volar/issues/1695) and other related aspects.
We could resolve identifiers when used in property initializers, like we do for object literal expressions. I'm interested to discuss a reasonable approach and maybe do the actual work.

Add tests for props declared via definition constants

---

extensions/vscode-vue-language-features/README.md

docs: add guide of global components for vue 2

---

packages/vue-language-core/src/generators/template.ts

Fixes johnsoncodehk/volar#1560
In some cases the template generator sets the `style` property to `undefined` , which is not accepted by TypeScript when `exactOptionalPropertyTypes: true` in `tsconfig.json`.
This PR changes the template generator to emit empty string (`""`) instead of `undefined`  for `style` in those cases.

Set style property to "" instead of to undefined

---

extensions/vscode-vue-language-features/package.json

This makes it correctly detect that Vite is ready again after a Vite restart from config changes.

Update vite problemMatcher endsPattern with "server restarted."

---

packages/vue-language-server/src/commonServer.ts

When volar is used with LSP clients which doesn't support `workspaceFolders`, the exception from the following part is raised.
https://github.com/microsoft/vscode-languageserver-node/blob/5c2e1065493290110bd7c7ea1b10cd6fa08eb81c/server/src/common/workspaceFolder.ts#L48-L50
So, I add code to check `workspaceFolders` capability also before registering `onDidChangeWorkspaceFolders` handler.

Check `workspaceFolders` capability before registering `onDidChangeWorkspaceFolders` handler

---

packages/typescript-language-service/src/configs/getUserPreferences.ts

[vscode reference](https://github.com/microsoft/vscode/blob/077f5865dac519a9ce6145b39065cee0b5952232/extensions/typescript-language-features/src/languageFeatures/fileConfigurationManager.ts#L192)
An example script, where you can take advantage. Unfortunately I didn't figure out a way to enable object literal method completions in `js` lang (but in theory it works fine in both).
```vue
<script lang="ts">
import Vue, { defineComponent, Component } from 'vue'
defineComponent({
activated // trigger
activated() {
}
})
interface Test {
callback()
}
class TestImpl implements Test {
callback // trigger
callback() {
}
}
</script>
```
While the first case is useful specifically in vue sfc, second case is still useful when using takeover mode.
I checked this only in VSCode.

Enable class/object literal method completions

---

.vscode/launch.json
examples/svelte/.vscodeignore
examples/svelte/LICENSE
examples/svelte/README.md
examples/svelte/package.json
examples/svelte/src/client.ts
examples/svelte/src/server.ts
examples/svelte/tsconfig.build.json
pnpm-lock.yaml
pnpm-workspace.yaml
tsconfig.build.json
tsconfig.json

This PR show how to create a Svelte language server via Volar framework. Please note that API will change at any time before v1.0, this is just for preview for now.
To try it, you can run "Launch Svelte Example".

feat: svelte language server example

---

examples/svelte/src/server.ts
extensions/vscode-vue-language-features/package.json
extensions/vscode-vue-language-features/src/common.ts
packages/language-server/src/features/customFeatures.ts
packages/language-server/src/registers/registerlanguageFeatures.ts
packages/language-server/src/server.ts
packages/language-server/src/types.ts
packages/language-server/src/utils/documentServiceHost.ts
packages/language-server/src/utils/project.ts
packages/language-server/src/utils/workspaceProjects.ts
packages/language-server/src/utils/workspaces.ts
packages/vue-component-meta/src/index.ts
packages/vue-language-core/src/languageModule.ts
packages/vue-language-core/src/plugins/file-html.ts
packages/vue-language-server/src/index.ts
packages/vue-language-server/src/plugin.ts
packages/vue-language-server/src/types.ts
packages/vue-language-service/src/documentService.ts
packages/vue-language-service/src/languageService.ts
packages/vue-typescript/src/index.ts

To enable language support for petite-vue / VitePress, you need to setting `"volar.vueserver.petiteVue.processHtmlFile": true`, `"volar.vueserver.vitePress.processMdFile": true` in workspace VSCode settings.
close #1471, close #1852

feat: Config petite-vue, VitePress supports in settings

---

extensions/vscode-vue-language-features/package.json
packages/vue-language-core/src/plugins/vue-sfc-styles.ts

Less support was left out in the initial pull request https://github.com/johnsoncodehk/volar/pull/1822
This pull request corrects that

Add less support for initial indent in non-template regions

---

packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/parsers/scriptRanges.ts
packages/vue-language-core/src/plugins/vue-tsx.ts
packages/vue-language-core/src/sourceFile.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/localTypes.ts
packages/vue-language-core/src/utils/string.ts
packages/vue-language-service/src/plugins/vue-template.ts

When project include lot of vue files, cache template AST / SFC parse result / codegen data memory overhead is high, it is necessary for better DX, but we can only cache for last editing vue file instead of cache for all project vue files.

perf: reduce VueSourceFile overhead memory usage

---

extensions/vscode-vue-language-features/src/features/tsVersion.ts

When clicking the `What's is Takeover Mode` option in VSCode, it navigates to the top of the overview page instead of the Volar Takeover Mode section.

doc: update reference to the takeover mode in the Vue docs

---

extensions/vscode-vue-language-features/src/features/doctor.ts

Added csstools.postcss and vunguyentuan.vscode-postcss as alternative PostCSS syntax highlighters.

feat(doctor): added more postcss syntax highliters

---

vue-language-tools/vue-language-core/schemas/vue-tsconfig.schema.json
vue-language-tools/vue-language-core/src/generators/script.ts
vue-language-tools/vue-language-core/src/sourceFile.ts
vue-language-tools/vue-language-core/src/types.ts
vue-language-tools/vue-language-core/src/utils/ts.ts

RFC: https://github.com/vuejs/rfcs/discussions/436
```jsonc
{
"jsxTemplates": true,
"experimentalRfc436": true
}
}
```
Please note that `extends any` is required, otherwise JSX syntax will be broken.
```html
<script setup lang="ts" generic="T extends any">
defineProps<{ msg: T }>()
</script>
```

feat: Support RFC 436 (Experimental)

---

vue-language-tools/vue-language-core/src/generators/script.ts
vue-language-tools/vue-language-core/src/generators/template.ts
vue-language-tools/vue-language-core/src/utils/localTypes.ts

Update codegen for script setup to change export component type from `DefineComponent` to functional component.
For following SFC code:
```html
<template>
<slot name="default" :test="props.msg"></slot>
</template>
<script lang="ts" setup generic="T">
const props = defineProps<{ msg: T }>()
</script>
```
Output type:
```ts
<T>(__props: { msg: T }): {
props: typeof __props,
children: { default(_: { test: T }): any },
}
```
`vue-component-meta` tests is broken because we not yet implement type extract for functional component in `vue-component-meta`.

feat: Support generic typed template slots for RFC 436

---

vue-language-tools/vue-language-core/schemas/vue-tsconfig.schema.json
vue-language-tools/vue-language-core/src/plugins/vue-template-html.ts
vue-language-tools/vue-language-core/src/types.ts
vue-language-tools/vue-language-core/src/utils/ts.ts

Due to we have add `resolveTemplateCompilerOptions` API for VueLanguagePlugin (https://github.com/johnsoncodehk/volar/commit/079e9ba9d37010bb3b36f6219ca85d76cb308ab7), `experimentalTemplateCompilerOptions` and `experimentalTemplateCompilerOptionsRequirePath` will be remove in `vueCompilerOptions`.
- `tsconfig.json`
```diff
{
"vueCompilerOptins": {
-		"experimentalTemplateCompilerOptionsRequirePath": "./myOptions.js",
+		"plugins": ["./myOptions.js"],
}
}
```
- `myOptions.js`
```diff
-export deault { /* my options */ };
+ module.exports = () => ({
+	version: 1,
+	resolveTemplateCompilerOptions(originalOptions) {
+		return {
+			...originalOptions,
+			/* my options */
+		};
+	},
+});
```
cc @theolavaux, @fletcherhaz

refactor: remove `experimentalTemplateCompilerOptions`

---

extensions/vscode-vue-language-features/src/features/doctor.ts

Saw the new `doctor.ts` feature. Super helpful!
Suggesting some changes to the generated doc regarding wording.

docs: add clarity to doctor.ts text; fix typos

---

extensions/vscode-vue-language-features/package.json
extensions/vscode-vue-language-features/src/common.ts
plugins/json/src/index.ts
vue-language-tools/vue-language-server/src/languageServerPlugin.ts
vue-language-tools/vue-language-server/src/types.ts
vue-language-tools/vue-language-service/src/languageService.ts

Implement https://github.com/johnsoncodehk/volar-plugins/pull/17 in json plugin.
@kingyue737 we can add default urls config for `volar.vueserver.json.customBlockSchemaUrls`, please feel free to PR if you know some valid json schema links for custom blocks.

feat: support `volar.vueserver.json.customBlockSchemaUrls`

---

packages/preview/bin/vite/config.ts

It can't preview the webpage in the VSCode when the project is with ArcoVue(@arco-design/web-vue, a UI framework powered by ByteDance), because of the main JavaScript file of ArcoVue is "@arco-design_web-vue.js", the script will inject into this file too.

fix: Fix the inaccurate judgment of "vue.js"

---

extensions/vscode-vue-language-features/src/browserClientMain.ts
extensions/vscode-vue-language-features/src/common.ts

Currently the vue language server does not start in vscode web even though web compatible server is available because of following reasons
* it tries to get tsserver path which is not supported
```
Uncaught (in promise) TypeError: ry.getCurrentTsdk is not a function
at iy (client.js?target=web:62:12469)
at eval (client.js?target=web:62:7509)
at Generator.next (<anonymous>)
at eval (client.js?target=web:62:6338)
at new Promise (<anonymous>)
at Br (client.js?target=web:62:6135)
at sf (client.js?target=web:62:7313)
at i (client.js?target=web:62:7145)
at eval (client.js?target=web:62:6962)
at Generator.next (<anonymous>)
at eval (client.js?target=web:62:6338)
at new Promise (<anonymous>)
at Br (client.js?target=web:62:6135)
at LP (client.js?target=web:62:6881)
at KP …
```

fix: vue language server not starting in vscode web

---

vue-language-tools/vue-language-core/schemas/vue-tsconfig.schema.json
vue-language-tools/vue-tsc/src/proxy.ts

This PR support setting a TS Program callback script for `vue-tsc` in `vueCompilerOptions`.
The TS program can pass to 3rd tools like ESLint to use.
For ESLint, reusing TS Program can get better performance in CI/CD and some other benefits. (See #2204)
This is not a complete vue-tsc + ESLint solution, we may have a separate module for working with experimentalTscProgramCallbacks to support ESLint.
- tsconfig.json
```json
{
"experimentalTscProgramCallbacks": ["./vueTscProgramCallback.js"]
}
}
```
- vueTscProgramCallback.js
```js
/**
* @param {import('typescript').Program} program 
*/
module.exports = function (program) {
const rawInputFiles = program.__vue.options.rootNames; // .ts and .vue files
const rawTsFilesAndVirtualTsFiles = …
```

feat(vue-tsc): `experimentalTscProgramCallbacks`

---

packages/vscode-language-client/src/features/autoInsertion.ts

fix: auto complete ref value with '.value' not working

---

examples/vue-and-svelte-language-server/src/index.ts
packages/language-server/src/common/project.ts
packages/language-server/src/common/syntaxServicesHost.ts
packages/language-server/src/common/utils/serverConfig.ts
packages/language-server/src/common/workspace.ts
vue-language-tools/vue-component-meta/src/index.ts
vue-language-tools/vue-language-core/schemas/vue-tsconfig.schema.json
vue-language-tools/vue-language-core/src/languageModule.ts
vue-language-tools/vue-language-core/src/types.ts
vue-language-tools/vue-language-core/src/utils/ts.ts
vue-language-tools/vue-language-server/src/languageServerPlugin.ts
vue-language-tools/vue-language-service/src/documentService.ts
vue-language-tools/vue-language-service/src/languageService.ts
vue-language-tools/vue-tsc/src/index.ts
vue-language-tools/vue-typescript/src/index.ts

Add `vueCompilerOptions.experimentalAdditionalLanguageModules` option to support config additional LangaugeModule, it can be used to generate virtual files for arbitrary source files other than .vue, or to add global virtual files.
Note that this option is only available when the TypeScript Plugin or Takeover mode is enabled.
And `Show Virtual Files` command only works for generated virtual files from source files, for global virtual files you can only debug with `Write Virtual Files` command for now.
- `tsconfig.json`:
```json
{
"experimentalAdditionalLanguageModules": ["./nuxt-virtual-files.js"]
}
}
```
- `nuxt-virtual-files.js`:
```js
/**
* @type {import('@volar/language-core').LanguageModule}
*/
module.exports = {
createFile() {
return;
},
updateFile() { …
```

feat: Support for Additional Language Modules (Experimental)

---

vue-language-tools/vue-component-meta/src/index.ts
vue-language-tools/vue-component-meta/src/types.ts

This PR makes schema resolve on demand when accessing schema, it maybe avoids some crash cases. And `schema: true` are not needed anymore due to on-demand resolve.
cc @stafyniaksacha, @antfu
---
Btw after reviewing the current implementation, I think that for more complex use cases, users should be advised to use rawType to resolve themselves.

perf(vue-component-meta): resolve schema on demand

---

vue-language-tools/vscode-vue/src/features/doctor.ts

Mismatch in url after moving extensions to vue-language tools

Updated view source code link

---

lerna.json

since you're using Lerna-Lite, it would be better to use Lerna-Lite's JSON Schema instead of Lerna's Schema which is slightly different. Also note that I'm the maintainer of Lerna-Lite ;)

chore: should be using Lerna-Lite schema instead of Lerna schema

---

packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/utils/localTypes.ts
packages/vue-test-workspace/vue-tsc/#2370/main.vue

Fixes #2370.
As for now Volar generates code like this when `defineEmits` is used with empty interface:
```ts
type __VLS_ConstructorOverloads<T> =
// 0
T extends {
} ? (
) :
// 0
{};
```
which is not valid TypeScript code. This PR skips the `nums == 0` case.

fix: `genConstructorOverloads` when nums is 0

---

packages/vue-tsc/bin/vue-tsc.js
packages/vue-tsc/src/index.ts

Undo #1402, Fix #2316.
The motivation is that somehow vue-tsc does not fully support tracing. Compared with tsc, vue-tsc silently lost some output, which caused some users to be unable to continue debugging.
Here's the related discussion: https://discord.com/channels/793943652350427136/1025627001102544957/threads/1058554813626982440
A more reliable method is to use the `Write Virtual Files` command + tsc instead.
cc @blake-newman.

feat(vue-tsc): unsupport tracing

---

packages/vue-test-workspace/format/js template strings/input.vue
packages/vue-test-workspace/format/js template strings/output.vue
packages/vue-test-workspace/format/js template strings/settings.json
packages/vue-test-workspace/format/multi-line html comment/input.vue
packages/vue-test-workspace/format/multi-line html comment/output.vue

Indentation should not be modified in some cases, such as html comments and js string templates.
Needs:
- https://github.com/volarjs/volar.js/commit/86007dcc0e1d692adc2c197f5efa835ab9d3f131
- https://github.com/volarjs/plugins/commit/0cf6d083b70c5cd2d7cc736ad3d764a4fb61b1b7
- https://github.com/volarjs/plugins/commit/a734f87f0ae8903c00e3ff2c4db3350cc2ca1e75

chore: add format test for indent sensitive cases

---

packages/vscode-vue/package.json
packages/vscode-vue/src/common.ts

`volar.vueserver.fullCompletionList` is used to control if the language server should filter completion items first or not for better JSON decode performance. Default false (should filter).
Implement by https://github.com/volarjs/volar.js/commit/fd0e24ca67f622aee2cad987221e21163e7aa963
Fix #2306

feat: add `volar.vueserver.fullCompletionList` setting

---

packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/utils/ts.ts

Fix #2415
@KaelWD proposes that the 	`v-model` type of the input tag should not correspond to `checked`: https://github.com/vuejs/language-tools/issues/1252#issuecomment-1254806581

fix: looser `v-model` type behavior for checkbox, radio input tag

---

tsconfig.json

Our current build target is ES2016, but the core has been relying on the WeakRef feature of ES2021, so the code actually cannot run on runtimes that do not support ES2021.
After this PR, `vue-tsc`, `@volar/vue-language-server` will explicitly only support runtimes of node 16 or above.

Upgrade build target from ES2016 to ES2021

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/src/types.ts

Setting `globalPropNames` avoid parsing empty component `<script setup lang="ts"></script>` while creating new meta parser. which can save seconds when starting!
In actual vue 3.2, the resolved value is `[ 'key', 'ref', 'ref_for', 'ref_key', 'class', 'style' ]`

perf(vue-component-meta): delay init for global props list

---

packages/vue-language-core/schemas/vue-tsconfig.deprecated.schema.json
packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/ts.ts

Follow-up to #1964
- Volar / vue-tsc: v1.4.0
- Vue: v3.3
Note: Explicitly specify `@vue/jsx` to solve #592, if your node_modules does not include `@types/react` then `@vue/jsx` is not needed.
- `package.json`
```json
{
"devDependencies": {
"@vue/jsx": ">=3.3.0"
}
}
```
- `tsconfg.json`
```json
{
"compilerOptions": {
"jsxImportSource": "@vue/jsx"
},
"jsxTemplates": true
}
}
```
- Component
```html
<script setup lang="ts" generic="T">
defineProps<{ msg: T }>()
</script>
```
If in doubt about codegen behavior, you can inspect the virtual code with the `Volar (Debug): Show Virtual Files` command.

feat: RFC 436 Leaves Experimental

---

packages/vue-component-meta/src/index.ts
packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/plugins/vue-tsx.ts
packages/vue-language-core/src/utils/localTypes.ts

feat: Improve Typed Slots Support

---

packages/vue-language-core/src/utils/ts.ts

Have just tried https://github.com/vuejs/language-tools/pull/2267 and it totally didn't work because the path resolving always returned undefined.

fix: resolving of paths in vueCompilerOptions

---

packages/vue-tsc/src/index.ts

Typescript 5 will attempt to use the host `resolveModuleNameLiterals` if present, which prevents vue-tsc looking up Vue files.
Set this as undefined so it defaults back to existing logic.
---
I'm unsure on the api of `resolveModuleNameLiterals` so didn't try to implement a solution for this currently; thought it best to fallback to existing behavior and then discover if we get any benefits from using this API.

fix(vue-tsc): fix typescript 5 support

---

packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/parsers/scriptSetupRanges.ts
packages/vue-language-service/src/languageService.ts
packages/vue-language-service/src/plugins/vue.ts
packages/vue-test-workspace/vue-tsc/components/main.vue
packages/vue-test-workspace/vue-tsc/components/script-setup-generic.vue
packages/vue-test-workspace/vue-tsc/defineProp_B/main.vue
packages/vue-test-workspace/vue-tsc/generic-interface/main.vue
packages/vue-test-workspace/vue-tsc/script-setup-scope/export-order.vue

feat: fewer side effects codegen for `<script setup>`

---

packages/vue-language-core/src/utils/localTypes.ts
packages/vue-test-workspace/package.json
packages/vue-test-workspace/vue-tsc/type-helpers/main.vue
packages/vue-type-helpers/LICENSE
packages/vue-type-helpers/index.d.ts
packages/vue-type-helpers/package.json
pnpm-lock.yaml

Added `vue-type-helpers` to expose type helpers that can use for component dts built by vue-tsc.
- ComponentProps
- ComponentEmit
- ComponentSlots
- ComponentExposed

feat: add `vue-type-helpers` package

---

package.json
pnpm-lock.yaml

- in the next Lerna-Lite v2.0.0, I made `version` and `publish` as optional commands since it was requested by some users. So Lerna-Lite is now entirely modular and the user will need to manually install the command(s) he want to use (plus the CLI)
- I'm submitting this PR since your Lerna-Lite dependencies are set to `latest` and that will break your workflow, also note `version` is a strict dependency of `publish` which is why we can skip `version` install (we could also include it, it won't make a difference)
- see Lerna-Lite [v2.0.0-alpha.2](https://github.com/lerna-lite/lerna-lite/releases/tag/v2.0.0-alpha.2) release, I'm also expecting an official v2.0 release in a week or two

chore: Lerna-Lite 2.0 publish & version are becoming optional commands

---

packages/vscode-vue/client.js
packages/vscode-vue/server.js
packages/vscode-vue/src/nodeClientMain.ts

Supported Bun language server.
This PR is not user-oriented, because after testing, the performance of node executing TS LanguageService is 1.65 times faster than that of bun. The possible reason is that the TS team has been optimizing the performance of code running on node based on benchmarks. We're not going to switch to buns for now anyway until buns fix this in the future.
If you want to try it, please clone https://github.com/volarjs/workspace to use the latest commit of volar core, and hardcode to set bunPath: https://github.com/vuejs/language-tools/blob/2c36449d4c1095fd886df0be56a90aef4e1f50d7/packages/vscode-vue/src/nodeClientMain.ts#L64

feat: Bun-based language server (DEV only)

---

packages/vue-typescript/package.json

`@volar/vue-typescript` depends on `@volar/typescript` which has a peer dependency on `typescript` that it isn't providing.
This PR fixes that by declaring `typescript` as a peer dependency of `@volar/vue-typescript`

fix(vue-typescript): add missing peer dependency `typescript`

---

packages/vue-language-core/schemas/vue-tsconfig.deprecated.schema.json
packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/plugins/vue-tsx.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/ts.ts

In the past, we generated jsx format virtual code for templates based on the jsxTemplates option to obtain complete generic support, but with 1.4 substantially refactoring virtual code generation, we found a way to support generics for class components and functional components at the same time without relying on jsx , if you are interested in the principle, here is the playground link.
https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMQK4rAwEtUoIBhJAWwAdUQUMAueAHgBUA+AChpiRpoWAb3gA3MrhAt2AGnGSQQ+OwDaAXXgBfAJTwAvJ3hQUATwDcAKEuhIsBMnRZy0NGkq16jFihAB3Ni5efkERBQgpGXkJCKUZDW09Q3hRABI+AWUMUxoQJAAzeAzBbSsbcGg4eHz8QhIUYzQ8AmJSCmo6X0YOeQBpHmYVeQBrFl6dJksASHZ4EAAPDAZgNHhfAO4AOm3YAHNlE1Mko0P4AH5pqd65xeXVtOK0M5YiFHyQGHgABRC0LUupmd4MFMiwfpljsYzACfCAxB9pjIbksUCtgdtNnsDmZIacgexEWs4QjLA …

refactor: deprecate `jsxTemplates`

---

packages/vue-language-core/schemas/vue-tsconfig.deprecated.schema.json
packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/localTypes.ts
packages/vue-language-core/src/utils/ts.ts
packages/vue-language-server/src/languageServerPlugin.ts
packages/vue-language-service/src/helpers.ts
packages/vue-language-service/src/ideFeatures/nameCasing.ts
packages/vue-language-service/src/plugins/vue-template.ts
packages/vue-test-workspace/tsconfig.json

`nativeTags` was added for `jsxTemplates`, `jsxTemplates` has been removed in #2677, so `nativeTags` is no longer needed.

refactor: deprecate `nativeTags`

---

packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/sourceFile.ts
packages/vue-language-core/src/types.ts

Adds `attrs` property to `Sfc.customBlocks` to enable accessing custom block attrs through the Plugins API

feat: expose custom blocks attrs

---

packages/vue-component-meta/package.json
packages/vue-language-core/package.json

`@vue/language-core` tries to require `typescript` but doesn't declare it as a dependency.
This PR fixes that by declaring `typescript` as a peer dependency of `@vue/language-core`.
Ref https://github.com/yarnpkg/berry/actions/runs/4919080804/jobs/8786259067#step:5:63

fix(language-core): add missing peer dependency `typescript`

---

packages/vue-language-service/src/languageService.ts

Noticed this while working on my other PRs, I saw two forEachs over the item to avoid this.

perf(language-service): avoid looping through all items twice

---

package.json
packages/vscode-vue/package.json
packages/vue-component-meta/package.json
packages/vue-language-core/package.json
packages/vue-language-core/src/generators/template.ts
packages/vue-language-plugin-pug/package.json
packages/vue-language-server/package.json
packages/vue-language-service/package.json
packages/vue-tsc-eslint-hook/src/index.ts
packages/vue-typescript/package.json
pnpm-lock.yaml

Close #2366
Support 3 directive comment syntax for template.
`@vue-ignore`: Similar to `@ts-ignore`, ignore errors of the next template node. (Not just the next line)
`@vue-expected-error`: Similar to `@ts-expected-error`, report if the next template node has no errors.
`@vue-skip`: The next template node and its child nodes will skip generating virtual code.
```html
<template>
<HelloWorld :msg="wrongType" />
<HelloWorld :msg="wrongType" />
<SomethingYouDontWantVolarToRecognizeIt>
...
</SomethingYouDontWantVolarToRecognizeIt>
</template>
```

feat: Support for `@vue-ignore`, `@vue-skip`, `@vue-expected-error` directive comments

---

packages/vue-tsc/bin/vue-tsc.js

I'm using https://github.com/volarjs/volar.js for another project, and I used vue-tsc as an example of using Volar.
On my Volar project, I found this bug.
This was how I fixed it there. I don't know if this is a good approach.
Closes #2756

Fix vue-tsc and incremental cache

---

packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/utils/directorySharedTypes.ts
packages/vue-test-workspace/rename/duplicate-name-element/input/entry.vue
packages/vue-test-workspace/rename/duplicate-name-element/output/entry.vue

close #3226, close #3148, close #3130, close #2533
First I wasn't able to actually reproduce the problem, so please let me know if it doesn't solve the above closed issue. Thanks to @Fuzzyma for helping to investigate, I think the problem is most likely happening in #2685.
In this PR we no longer do type gymnastics with `JSX.IntrinsicElements`, so TS type evaluation may be faster.
But it also makes the template unable to separate `JSX.IntrinsicElements` and components types, which affects DX in some cases, but I think it is a reasonable trade-off, and it is too expensive to trade performance for it.

perf: Avoid doing type gymnastics with `JSX.IntrinsicElements`

---

package.json
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/utils/directorySharedTypes.ts
pnpm-lock.yaml

Changes:
- https://github.com/microsoft/TypeScript/issues/54630 is not only affected by module types, it is also affected by the `__VLS_componentProps` virtual code that breaks the event type checking, we move `& {}` inside `__VLS_PickNotAny` to fix it.
- Now always respect `vueCompilerOptions.htmlAttributes` (it used to only work when `strictTemplates` was enabled), otherwise valid virtual code for TS 5.1.3 cannot be generated. Since this option reduces virtual code, there may be a little TS performance improvement.

fix: compatible with TS 5.1.3

---

packages/vue-component-meta/src/index.ts
packages/vue-language-core/schemas/vue-tsconfig.deprecated.schema.json
packages/vue-language-core/schemas/vue-tsconfig.schema.json
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/types.ts
packages/vue-language-core/src/utils/ts.ts
packages/vue-language-server/src/languageServerPlugin.ts
packages/vue-language-service/src/helpers.ts
packages/vue-language-service/src/ideFeatures/nameCasing.ts
packages/vue-language-service/src/languageService.ts
packages/vue-language-service/src/plugins/vue-template.ts

close #3148
This PR is a rollback of #2685.
After confirmation, #3259 does not solve #3148. It seems that it is necessary to generate more efficient virtual code through the nativeTags of hard code, instead of entrusting the work of judging IntrinsicElements to TS.
This also fixed the regression introduced by #3259.
cc @ModyQyW

feat: redo `nativeTags`

---

packages/vue-component-meta/src/index.ts
packages/vue-component-meta/src/types.ts
packages/vue-component-meta/tests/index.spec.ts
packages/vue-component-type-helpers/index.d.ts
packages/vue-component-type-helpers/index.js

close #3151
Expose `type` property to meta:
- `0`: Unknown
- `1`: Component is a class type
- `2`: Component is a function type
cc @chakAs3

feat(component-meta): expose component type

---

packages/vue-test-workspace/vue-tsc/strict-template/#2726/main.vue

Moved the test for #2726 to `strict-template` directory as there was a TODO comment.

test: move the test for #2726 in strict-template directory

---

packages/vue-language-core/src/utils/directorySharedTypes.ts

Thus we don't have to use a hack to solve https://github.com/microsoft/TypeScript/issues/54630

refactor: simplify __VLS_IsAny

---

packages/vscode-vue/package.json

Removed previously deleted feature commands that remained in contributes.commands of the VSCode extension.

chore: remove serverStats command from package.json of VSCode extension

---

packages/vue-component-meta/tests/index.spec.ts
packages/vue-test-workspace/vue-component-meta/ts-component/component.ts
packages/vue-test-workspace/vue-component-meta/ts-component/component.tsx
packages/vue-test-workspace/vue-component-meta/ts-named-export/component.ts

Function Signature [​](https://vuejs.org/api/general.html#function-signature)
defineComponent() also has an alternative signature that is meant to be used with Composition API and [render functions or JSX](https://vuejs.org/guide/extras/render-function.html).
so I changed the test to match the new API and added test for JSX based component
```ts
// options syntax
function defineComponent(
component: ComponentOptions
): ComponentConstructor
// function syntax (requires 3.3+)
function defineComponent(
setup: ComponentOptions['setup'],
extraOptions?: ComponentOptions
): () => any
```

test: change defineComponent to support JSX

---

packages/vscode-vue/package.json
packages/vscode-vue/src/common.ts
packages/vscode-vue/src/config.ts
packages/vue-language-server/src/languageServerPlugin.ts
packages/vue-language-server/src/types.ts
packages/vue-language-service/src/languageService.ts

We added `json.customBlockSchemaUrls` in [1.0.10](https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md#1010-20221129) to solve a specific use case, but after Some time it is considered impractical now, the same problem can be solved through Volar's Services API.

Deprecate language server `json.customBlockSchemaUrls` option

---

packages/vscode-vue/src/common.ts
packages/vscode-vue/src/nodeClientMain.ts

Since output channels are created automatically right now, when you restart server, opened output channel disappears and you have to find it again... Right there is no api in vscode to focus specific output channel :(

Do not hide output channel on server restart :rocket:

---

packages/vue-language-core/src/utils/ts.ts

I want to parse config content after overriding and I found two methods: `createParsedCommandLine` and `createParsedCommandLineByJson`.
`createParsedCommandLine` parse config via path and cannot specify the config content.
`createParsedCommandLineByJson` will always set config path to `rootDir + '/jsconfig.json'`.
So it would be great if `createParsedCommandLineByJson` can support custom config path.

chore: support custom configPath for createParsedCommandLineByJson

---

packages/vscode-typescript-vue-plugin/README.md

doc: fix typo

---

packages/vue-component-type-helpers/index.d.ts
packages/vue-language-core/src/generators/script.ts
packages/vue-test-workspace/vue-tsc/non-strict-template/components/main.vue
packages/vue-test-workspace/vue-tsc/non-strict-template/defineProp_B/main.vue

close #3206, close vuejs/core#8373

fix(vue-component-type-helpers): correctly handle generic components when using `ComponentExposed`

---

packages/vue-tsc/bin/vue-tsc.js

Fix rebuilding in incremental mode with tsbuildinfo file causing error.
Secondary rebuilds cause the following error:
```
Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
```
This is caused because the mapping of the exportedModules looks for `__vls__` file id, but this has been removed in the other patches. This new patch filters this file which is virtual and removes it before mapping. This prevents the error occurring on rebuilds and composite mode. 
resolves: #3345
resolves: #2622

fix(vue-tsc): prevent rebuild in incremental mode throwing error

---

packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/utils/globalTypes.ts
packages/vue-test-workspace/vue-tsc/non-strict-template/#3561/Comp.vue
packages/vue-test-workspace/vue-tsc/non-strict-template/#3561/main.vue

close #3561
My implementation is terribly ugly so I need more time to refactor it.

fix: avoid losing generic types

---

packages/vue-language-core/src/generators/script.ts
packages/vue-language-core/src/generators/template.ts
packages/vue-language-core/src/parsers/scriptSetupRanges.ts
packages/vue-language-core/src/plugins/vue-tsx.ts
packages/vue-test-workspace/vue-tsc/non-strict-template/components/main.vue
packages/vue-tsc/tests/__snapshots__/dts.spec.ts.snap

For `defineSlots`, we can reuse its return type instead of generating duplicate virtual code for template.
For the following vue code.
```html
<script setup lang="ts">
defineSlots<{
activator?(props: { isActive: boolean }): void
}>();
</script>
<template>
</template>
```
```ts
/* script setup part */
// ...
defineSlots<{
activator?(props: { isActive: boolean }): void
}>();
// ...
/* template part */
var __VLS_slots!: {
activator?(props: { isActive: boolean }): void
};
// some template virtual codes reference __VLS_slots
```
```ts
/* script setup part */
// ...
const __VLS_slots = defineSlots<{
activator?(props: { isActive: boolean }): void
}>();
// ...
/* template part */
// some template virtual codes reference __VLS_slots
```

refactor: don't generate additional virtual code for `defineSlots`

---

packages/vue-language-core/src/generators/script.ts

close #3488
In the past, template virtual code used both `__VLS_publicComponent` and `__VLS_internalComponent` in order to reuse props types. Now it is changed to generate props option for `__VLS_publicComponent` and `__VLS_internalComponent` respectively, trading a little TS performance loss for accuracy.

reafctor: remove `__VLS_publicComponent`

---

README.md

The link to Volar's site (https://volarjs.github.io/) is no more available, and the repository (https://github.com/volarjs/volarjs.github.io) is read-only

Update the link to the Volar's site

---

packages/vue-language-core/src/generators/script.ts
packages/vue-test-workspace/vue-tsc/non-strict-template/#3615/Comp.vue
packages/vue-test-workspace/vue-tsc/non-strict-template/#3615/main.vue

fix: make emits type correct when user assigns emit function a custom name

---

packages/vscode-vue/package.json
packages/vscode-vue/tests/index.spec.ts
pnpm-lock.yaml

chore: rollback `vscode-languageclient` to 8.1.0

---

package.json
packages/typescript-vue-plugin/package.json
packages/vscode-vue/package.json
packages/vue-component-meta/package.json
packages/vue-language-core/package.json
packages/vue-language-plugin-pug/package.json
packages/vue-language-server/package.json
packages/vue-language-service/package.json
packages/vue-language-service/src/plugins/vue.ts
packages/vue-tsc-eslint-hook/package.json
packages/vue-typescript/package.json
pnpm-lock.yaml

In 1.8.16, due to upgrading vscode-languageclient v9, the extension cannot run on VSCode versions lower than 1.82.0. We revert to v8 in 1.8.17 to re-release 1.8.16 changes for users of lower versions.
This PR will re-upgrade the dependencies, and we will release 1.8.18 separately for the VSCode 1.82.0 upgrade.

Upgrade required VSCode version to 1.82.0

---

package.json
packages/typescript-vue-plugin/src/index.ts
packages/vscode-vue/package.json
packages/vue-component-meta/package.json
packages/vue-language-core/package.json
packages/vue-language-plugin-pug/package.json
packages/vue-language-server/package.json
packages/vue-language-service/package.json
packages/vue-typescript/package.json
packages/vue-typescript/src/index.ts
pnpm-lock.yaml

fix #3555, see https://github.com/microsoft/TypeScript/pull/56047
This only works for TS 5.3 or later tsserver, you need to wait for TS 5.3 to be released, or use `5.3.0-dev.*` for now.

feat(ts-plugin): Use TS 5.3 `updateLevel`

---

packages/vue-language-core/src/generators/script.ts

fix(language-core): export correct SlotsPropertyName for vue2

---

.github/workflows/release.yml

Hi, need this to have proper intellisense in stackblitz.
`ovsx publish` will automatically run `vscode:prepublish`, so no need to specify it again.

chore: publish ts plugin to open-vsx too

---

packages/language-core/src/generators/script.ts
packages/language-core/src/plugins/vue-tsx.ts
test-workspace/tsc/#3688/main.vue
test-workspace/tsc/#3688/tsconfig.json

fix(class references): experimentalResolveStyleCssClasses regression

---

package.json
packages/component-meta/package.json
packages/component-meta/src/index.ts
packages/language-core/package.json
packages/language-core/src/generators/script.ts
packages/language-core/src/languageModule.ts
packages/language-core/src/utils/ts.ts
packages/language-plugin-pug/package.json
packages/language-server/src/languageServerPlugin.ts
packages/language-service/package.json
packages/language-service/src/languageService.ts
packages/language-service/tests/utils/createTester.ts
packages/language-service/tests/utils/format.ts
packages/tsc/package.json
packages/tsc/src/index.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
packages/typescript-plugin/src/index.ts
pnpm-lock.yaml

Follow up https://github.com/volarjs/volar.js/pull/70

fix: Avoid downstream need node polyfill for browser

---

packages/language-core/src/parsers/scriptSetupRanges.ts

feat: expose `defineEmits`'s `arg` and `typeArg` in `parseScriptSetupRanges`

---

packages/tsc/tests/index.spec.ts

Test fails on slow RISC-V architecture.
Fix by increasing the timeout.
```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 7 ⎯⎯⎯⎯⎯⎯⎯
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (#2472)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (#3373)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (noPropertyAccessFromIndexSignature)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (vue2)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (vue2_strictTemplate)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (vue3)
FAIL  packages/tsc/tests/index.spec.ts > vue-tsc > vue-tsc no errors (vue3_strictTemplate)
Error: Test timed out in 40000ms.
If this is a long-running test, pass a timeout value as the last …
```

test: increate timeout for riscv64

---

extensions/vscode/syntaxes/vue.tmLanguage.json
test-workspace/language-service/syntax/directives.vue
test-workspace/language-service/syntax/dotprop-shorthand.vue

fix: syntax highlighting for `.prop` shorthand

---

packages/language-core/src/generators/template.ts
test-workspace/tsc/vue3_strictTemplate/dataAttributes/main.vue

Plain (native) elements should not have their props camelized as then the attribute names won't match the type definition if the element has those. For example `path` element defines type for the `stroke-width` attribute but since Volar "camelizes" the attribute name by default, it triggers type error due to `strokeWidth` not matching the `stroke-width` key.
I suppose the `ElementTypes.ELEMENT` type does not necessarily mean "native element" but hopefully it's close enough and correct to not camelize attributes by default for those elements.

fix: don't camelize attributes for plain elements

---

packages/component-meta/tests/index.spec.ts
packages/component-type-helpers/index.d.ts
packages/component-type-helpers/index.js
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/component-meta/generic/component.vue

fix(component-type-helpers): correct type inference for FunctionalComponent

---

extensions/vscode/package.json
package.json
packages/component-meta/package.json
packages/language-core/package.json
packages/language-core/src/generators/script.ts
packages/language-core/src/generators/template.ts
packages/language-core/src/languageModule.ts
packages/language-core/src/plugins.ts
packages/language-core/src/plugins/vue-tsx.ts
packages/language-core/src/types.ts
packages/language-plugin-pug/package.json
packages/language-server/package.json
packages/language-server/src/simpleServer.ts
packages/language-service/package.json
packages/language-service/src/helpers.ts
packages/tsc/bin/vue-tsc.js
packages/tsc/package.json
packages/tsc/src/index.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/package.json
pnpm-lock.yaml

This is a redo of #3534.
- The language server designates the first virtual file as the global types holder when it generates the first virtual file, and generates the helper types on it.
- vue-tsc creates additional dummy .vue files as global types holders to avoid global types emit to dts.
- Each project's global types holder is known at the time of generating virtual files. Using the holder file name as the file registry key safely avoids conflicts caused by duplicate helper types when multiple projects in the repo share virtual files.
- When the global types holder file is deleted, the global types holder is switched to another random file in the file registry (https://github.com/vuejs/language-tools/commit/d4c0c5e93ce3d434c726cd97a054350088d04c5f)

refactor(language-core): generate global types in one virtual file

---

README.md

Hello, I am currently using this project from within nvim via mason and was hoping to contribute.
I found that following the `README.md` to the discord link brought me to mostly NFT spam and unanswered community questions. I think it is probably best to remove this link until there is enough of a community around this project in particular to support moderation / questions from the community.
Also, if anyone can point me in a good direction to get information about a pipeline to build and load this within the nvim ecosystem I would really appreciate it.
Thanks for all your hard work!
```
there is no active moderation / community activity here. this is mostly filled with spam and unanswered questions.
```
Fixes N/A

chore(readme): update discord link

---

README.md

There is a link in the README.md that doesn't have an associated URL. 
It appears like this link url was [changed](https://github.com/vuejs/language-tools/commit/ce5623e52a31c99797052727a817d422266f210d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to a path that doesn't exist. The previous URL seems to be the correct location for the extension source code. My context to this repo is very low and this is my first OS contribution, let me know if I am missing something 👍

fix: revert url to previous working url in readme

---

packages/component-meta/src/base.ts
packages/language-core/schemas/vue-tsconfig.deprecated.schema.json
packages/language-core/schemas/vue-tsconfig.schema.json
packages/language-core/src/languageModule.ts
packages/language-core/src/types.ts
packages/language-core/src/utils/ts.ts
packages/language-server/src/nodeServer.ts
packages/language-service/src/index.ts
packages/language-service/src/plugins/css.ts
packages/language-service/src/plugins/typescript.ts
packages/language-service/src/plugins/vue-sfc.ts
packages/language-service/src/plugins/vue-template.ts
packages/language-service/tests/utils/createTester.ts
packages/language-service/tests/utils/format.ts
packages/tsc/src/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/src/index.ts

- Remove deprecated `createLanguages` API
- `createVueLanguage` API rename to `createVueLanguagePlugin`
- No longer support for `experimentalAdditionalLanguageModules`, alternatives will be provided (probably after v2 is released)

refactor(language-core): remove `experimentalAdditionalLanguageModules` and deprecated APIs

---

packages/language-core/src/generators/template.ts
pnpm-lock.yaml
test-workspace/package.json
test-workspace/tsc/vue2_strictTemplate/#3881/main.vue
test-workspace/tsc/vue2_strictTemplate/tsconfig.json

Explained all in #3881
Fixes #3881

fix: address transition type incompatibility with Vue 2.7.16

---

extensions/vscode/syntaxes/vue-directives.json

Vue directive syntax captures take over required terminating characters for expressions inside Angular template bindings. These bindings are identifiable with `meta.ng-binding` (https://github.com/angular/vscode-ng-language-service/blob/5d73b53115db57ea868f11aa5caa4bc0d890bb12/syntaxes/template-tag.json#L43).
https://github.com/angular/vscode-ng-language-service/issues/1989 https://github.com/angular/vscode-ng-language-service/issues/2005
reviewer note: I'm the maintainer of the Angular VSCode extension. While I don't think it's necessary that we always maintain compatibility, it would be nice if our syntaxes played nicely together when there are simple solutions. This seemed like the cleanest solution but I'm open to other suggestions. I built this extension locally and it seems to …

fix: exclude vue directive syntax injection in Angular bindings

---

packages/component-meta/tests/index.spec.ts
packages/language-core/src/generators/script.ts
packages/language-core/src/parsers/scriptSetupRanges.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/component-meta/reference-type-model/component.vue
test-workspace/tsc/vue2/tsconfig.json
test-workspace/tsc/vue3/defineModel/main.vue

Added defineModel emit definition code generation, i.e. `update:{propName}`
I've also added the missing test for defineModel in component-meta
I belive it fix #3894

feat(language-core): add emit codegen for defineModel

---

packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
packages/typescript-plugin/lib/requests/getPropertiesAtLocation.ts
packages/typescript-plugin/lib/server.ts

The call to `provideAutoInsertionEdit` is too eager (called 100ms after the document is changed). At this time, the tsserver may not have obtained the latest script changes, and the requested position parameter may be calculated at the wrong position.
Even if an additional version is used to check whether the tsserver script has been synchronized, it does not mean that the type checker is currently available, because the tsserver must wait for the diagnosis to be completed to synchronize the internal state. If the TS API is called in advance in the request handle, it will also cause the tsserver status to be abnormal.
It is currently difficult to find a way to reliably handle tsserver state synchronization, so this PR simply waits 250ms to bypass the problem.

fix(language-service): wait for tsserver to be ready when requesting auto insert `.value`

---

packages/language-core/lib/plugins.ts
packages/language-core/lib/plugins/vue-sfc-customblocks.ts
packages/language-core/lib/plugins/vue-sfc-scripts.ts
packages/language-core/lib/plugins/vue-sfc-styles.ts
packages/language-core/lib/plugins/vue-sfc-template.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-core/lib/types.ts
packages/language-core/lib/virtualFile/computedFiles.ts
packages/language-core/lib/virtualFile/embeddedFile.ts

The Plugin API changed from v1 to v2, but please note that there are no improvements here, it is just a renaming of part of the API to match Volar v2's terminology.
- `getEmbeddedFiles` -> `getEmbeddedCodes`
- `VueEmbeddedFile` -> `VueEmbeddedCode`
- `parentFileId` -> `parentCodeId`
- `resolveEmbeddedFile` -> `resolveEmbeddedCode`

refactor(language-core): plugin api v2

---

packages/typescript-plugin/index.ts
packages/typescript-plugin/lib/client.ts
packages/typescript-plugin/lib/server.ts
packages/typescript-plugin/lib/utils.ts

- Warnings are not reported when filtering invalid named pipe servers
- Select Inferred Project based on workspace path instead of pid
- Each time a request is sent to the named pipe server, the connection is initiated once instead of twice
- Named pipe servers table json file name includes version number to prevent language servers from establishing connections with incompatible named pipe servers.
closes #3931, closes #3927

fix(typescript-plugin): more reliable connection to named pipe server

---

packages/language-server/node.ts
packages/language-server/package.json
packages/language-service/index.ts
packages/language-service/lib/ideFeatures/nameCasing.ts
packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
packages/language-service/lib/plugins/vue-extract-file.ts
packages/language-service/lib/plugins/vue-template.ts
packages/language-service/lib/plugins/vue-twoslash-queries.ts
packages/language-service/package.json
pnpm-lock.yaml

Fix browser support for https://github.com/vuejs/repl/pull/225

refactor(language-service): dependency injection typescript plugin

---

README.md

The README contains no direct reference to the language server itself. Given past  renames and the legacy Vetur, it's not straightforward to fine the correct package online.
Include the LSP and its package name in the README. This will assist people trying to install the language server.
Additionally, as of 2.0.0, a plug-in is required for TypeScript support. This is mentioned in the changelog, but the name of the plug-in itself is not made evident anywhere. Also add this to the README.

Add LSP package name to the readme

---

packages/language-server/node.ts
packages/typescript-plugin/lib/client.ts
packages/typescript-plugin/lib/server.ts

Fixes #3937
This problem can be reproduced with https://github.com/elk-zone/elk. The result length of getComponentNames is 17823 in elk, which is greater than the 8192 limit that can be received at a time, thus causing JSON parsing to fail with incomplete result.

fix(typescript-plugin): JSON parsing error when server data length > 8192

---

packages/component-meta/lib/base.ts
packages/language-core/lib/generators/script.ts
packages/language-core/lib/languageModule.ts
packages/language-core/lib/plugins.ts
packages/language-core/lib/types.ts
packages/language-server/node.ts
packages/language-service/tests/utils/createTester.ts
packages/language-service/tests/utils/format.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/index.ts

This fix fixes the issue where `globalTypesHolder` in the nuxt project is specified as a vue file in `node_modules`, causing the global type to be missing in the project root vue files.

fix(language-core): avoid `globalTypesHolder` being specified from a `node_modules` file

---

packages/language-core/lib/generators/template.ts
test-workspace/tsc/vue3/#3997/main.vue

fix: use local variables in v-bind shorthand

---

packages/language-server/typescript-plugin.ts
packages/typescript-plugin/README.md

Re-export the typescript plugin from `@vue/language-server/typescript-plugin` to avoid users having to ensure version consistency themselves.

refactor(language-server): re-export `@vue/typescript-plugin`

---

README.md

The tutorial for setting up Volar 2.0 on NeoVim has been updated. 
The use of multiple servers is no longer applicable in the new version. 
To help users who are updating Volar on Neovim quickly find the correct configuration, issue #3925 serve as the new link.

docs(language-service): update neovim lsp set up info

---

extensions/vscode/package.json

The language ID isn’t needed for injections. Only `scopeName` is needed. The language ID appears in the VSCode language selector, which isn’t desired behaviour.
This is based on https://github.com/microsoft/vscode/issues/207406#issuecomment-1991393649. Also I didn’t notice problems when trying this myself.

chore(vscode): remove embedded language IDs

---

packages/language-core/lib/generators/script.ts
test-workspace/tsc/vue3/#4050/main.vue

fix(language-core): generate `defineModel` emits type on-demand

---

README.md

The length of this issue continues to increase. I believe that posting the configuration directly in the README would be more straightforward for anyone seeking help.

docs: update readme with neovim lspconfig setup

---

packages/language-core/lib/generators/inlineCss.ts
packages/language-core/lib/generators/template.ts
packages/language-core/lib/plugins.ts
packages/language-core/lib/plugins/vue-sfc-styles.ts
packages/language-core/lib/plugins/vue-template-inline-css.ts
packages/language-core/lib/plugins/vue-template-inline-ts.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-core/lib/virtualFile/computedFiles.ts
packages/language-service/lib/plugins/vue-autoinsert-parentheses.ts
packages/language-service/tests/format/2105.spec.ts
packages/language-service/tests/format/deep-interpolation-indent.spec.ts

close #3973, #4078
After Volar 2.1, there has been a change in the handling of indentation for embedded code. It now only calculates the initial indentation of the entire virtual document instead of the each interpolation segment. Therefore, each interpolation segment now needs to be generated into a separate virtual document so that Volar can handle the initial indentation of each segment independently.

fix(language-core): generate each interpolation into separate virtual code

---

extensions/vscode/package.json
extensions/vscode/src/common.ts

close #4164
In versions 2.0.0 ~ 2.0.6, TS support in .vue files was provided by tsserver. The "TypeScript: Restart TS Server" command should be used instead of the original restart command, so the original restart command has been removed.
In version 2.0.7, full TS support was re-implemented by the Vue server, so the restart vue server command is needed again.
The situation is a bit confusing in 2.0.7:
- When Hybrid Mode is disabled, the restart command should restart the vue language server.
- When Hybrid Mode is enabled, the restart command should restart tsserver.
To avoid confusion, the restart command will now always restart both the vue language server and tsserver.

feat(vscode): re-add restart server command

---

packages/tsc/tests/__snapshots__/dts.spec.ts.snap
packages/tsc/tests/dts.spec.ts
test-workspace/component-meta/empty-component/custom-extension-component.cext
test-workspace/component-meta/generic/custom-extension-component.cext

Adds two simple tests for vue-tsc to ensure volarjs/volar.js#155 is working correctly. So this should not be merged until that is merged.
These basically duplicate two of the existing `component.vue` test files with a custom extension and then update the dts suite to enable that custom extension.

Added simple tests for vue-tsc and custom SFC extensions.

---

packages/component-meta/lib/base.ts
packages/component-meta/tests/index.spec.ts
packages/language-core/lib/generators/script.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/component-meta/reference-type-model/component.vue

This PR aims to retrieve types of model modifiers from `defineModel` macro.
```ts
// default
const [modelValue, modelModifiers] = defineModel<string, 'lazy' | 'trim'>()
// modelValue: import("vue").PropType<string>
// modelModifiers: import("vue").PropType<Record<'lazy' | 'trim', true>>
// named
const [named, modifiers] = defineModel<string, 'foo'>('named')
// named: import("vue").PropType<string>
// namedModifiers: import("vue").PropType<Record<'foo', true>>
```
Here is a playground where we can see property being generated: https://play.vuejs.org/#eNqFkk1PwzAMhv+KlUtBqrYDnKZuEqAdQOJDgLgQDlHrlow0iZJ0DEr/O26qlQlN2y1+/dp+bKVlF9ZO1g2yGct87qQN4DE0FpTQ1Zyz4DlbcJ0b7QO81qZA9SJUgynE960pZCnR+TeYQ4Gl1EgSqswHJ3WVQqLE91cCP5CQUCeLk9OxmRY1FrHPkRalMVSYRH9C9dl0ICUuCgLWVomAFAFk1uGibaHtAxgY9/Kmg+E/Q5Q76Lps …

feat(component-meta): add typing resolution for defineModel modifiers

---

packages/language-core/lib/generators/globalTypes.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts

composite projects currently do not rebuild efficently because we attach a fake place holder vue file. This is used to generate global types once for the project.
As the fake placeholder file is added the the roots file, the second build will detect a change because the root file does not exist for discovery with tsc.
> Project 'packages/design-system/tsconfig.json' is out of date because buildinfo file
> 'packages/design-system/tsconfig.tsbuildinfo' indicates that file '[.../path/to/fake-file.vue]'
> was root file of compilation but not any more.
remove adding the fake file to the roots, and instead apply the globals to the first vue file and then remove them when writing .d.ts.

fix(tsc): remove fake global types holder

---

extensions/vscode/package.json
extensions/vscode/src/common.ts
extensions/vscode/src/config.ts
extensions/vscode/src/features/doctor.ts
extensions/vscode/src/nodeClientMain.ts

Closes #4131
This introduces the default value of `"auto"` for `vue.server.hybridMode`, which automatically enables it based on the compatibility of installed TS plugin extensions with Hybrid Mode.
The following TS plugin extensions are currently known to be compatible:
- unifiedjs.vscode-mdx
- astro-build.astro-vscode
- ije.esm-vscode
- johnsoncodehk.vscode-tsslint
- VisualStudioExptTeam.vscodeintellicode
The following TS plugin extensions are currently known to be incompatible:
- styled-components.vscode-styled-components
- svelte.svelte-vscode
- Divlo.vscode-styled-jsx-languageserver
If you know of any other compatible TS plugin extensions, please report them here so that we can update the whitelist.
To verify compatibility, simply set `"vue.server.hybridMode": true` in your VSCode …

feat(vscode): automatically enable Hybrid Mode

---

packages/language-server/lib/hybridModeProject.ts
packages/language-server/node.ts
packages/typescript-plugin/lib/client.ts
packages/typescript-plugin/lib/server.ts
packages/typescript-plugin/lib/utils.ts

Fixes #3959
Even if Hybrid Mode is enabled, the project should still be created based on tsconfig. This is to ensure that the template compiler/codegen can use the `compilerOptions` and `vueCompilerOptions` in tsconfig.
To ensure tsconfig options consistency with the tsconfig path displayed in the status bar, it is necessary to communicate with the tsserver to obtain a matching tsconfig instead of searching in LSP server.

feat(language-server): create project with tsconfig on hybrid mode

---

packages/tsc/tests/index.spec.ts
test-workspace/tsc/should-error/main.vue
test-workspace/tsc/should-error/tsconfig.json

This MR is in reaction to #4203

vue-expect-error is not failing tests when it should

---

extensions/vscode/package.json
extensions/vscode/src/common.ts
extensions/vscode/src/config.ts
extensions/vscode/src/nodeClientMain.ts

When Hybrid Mode is explicitly or automatically disabled, `@vue/typescript-plugin` will no longer be effective by default to avoid potential crashes of tsserver.
A new option `"vue.server.hybridMode": "typeScriptPluginOnly"` is introduced, to address which allows users to still enable `@vue/typescript-plugin` when Hybrid Mode is disabled.
For explanations of all states, please refer to:
https://github.com/vuejs/language-tools/pull/4226/files#diff-288f1ebddf6afc6081e2ca910029e86e55c9cd7871b425c2a97a82a2cd77ac9eR231-R236

feat(vscode): support for disabling typescript plugin

---

packages/language-core/lib/utils/ts.ts

Added support for search element. It has had widespread browser support since october 2023
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

feat(language-core): added search html tag

---

packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementProps.ts
packages/language-core/lib/codegen/template/slotOutlet.ts

When executing go to definition on component prop, it should jump directly to the prop definition instead of popping up a peek window.

fix(language-core): reduce unnecessary props mapping

---

packages/tsc/index.ts

The issue with the removal of global types was the RegExp, for certain files written like `.tsbuildinfo` which is a single line long contents file it would scan the whole line scanning for the characters.
By specifying `m` flag it causes `^` and `$` to match the begin/end of each line (not only begin/end of string).
This removes the need for the check of the filename to do the replacement check.

fix(tsc): improve regexp performance for global type removal

---

extensions/vscode/package.json
extensions/vscode/src/common.ts
extensions/vscode/src/config.ts
extensions/vscode/src/features/doctor.ts
extensions/vscode/src/features/nameCasing.ts
extensions/vscode/src/nodeClientMain.ts
packages/component-meta/lib/base.ts
packages/language-core/lib/languageModule.ts
packages/language-core/lib/plugins.ts
packages/language-core/lib/plugins/file-html.ts
packages/language-core/lib/plugins/file-md.ts
packages/language-core/lib/types.ts
packages/language-core/lib/utils/ts.ts
packages/language-core/schemas/vue-tsconfig.schema.json
packages/language-server/lib/types.ts
packages/language-server/node.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/index.ts
packages/typescript-plugin/lib/common.ts

Fixes #4251
In the past, the behavior of configuring additional extensions, VitePress and PetiteVue was inconsistent between IDEs and `vue-tsc` is inconsistent.
For example, when `"vue.server.additionalExtensions": ["nvue"]` is configured, but `vueCompilerOptions` is set to default:
- `.nvue` files become project files for the Vue language server.
- `.nvue` files do not become project files for `vue-tsc`.
- The Vue language server can monitor `.nvue` files.
When `vueCompilerOptions: { "extensions": [".vue", ".nvue"] }` is configured, but `vue.server.additionalExtensions` is set to default:
- `.nvue` files become project files for the Vue language server.
- `.nvue` files become project files for `vue-tsc`.
- The Vue language server cannot monitor `.nvue` files.
This PR is to address this …

feat: redesign additional extensions, VitePress, PetiteVue support

---

packages/language-core/lib/codegen/script/scriptSetup.ts
test-workspace/tsc/vue3/#4326/main.vue

```ts
const { bottom } = __VLS_slots; 
const __VLS_slots = defineSlots<{
bottom: (props: { num: number }) => any[],
}>()
```

fix(language-core): correct logic for defineSlots destructuring

---

packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/interpolation.ts
packages/language-core/lib/parsers/scriptRanges.ts
packages/language-core/lib/types.ts
packages/language-core/lib/utils/ts.ts
packages/language-core/schemas/vue-tsconfig.schema.json
test-workspace/tsc/vue3/#997/main.vue

Re-fix #997, `vueCompilerOptions.experimentalUseElementAccessInTemplate` is now deprecated.

feat(language-core): proper support for class component

---

README.md

Dear Developers and Community,
Sincere gratitude for the magic and work you do...
Reason: The identical reference is already stated in the list in:
```md
[`@vue/language-server`](/packages/language-server/) // ...
```
---
Best and kind regards :sparkles:

Removed possibly redundant duplicate reference

---

.github/workflows/auto-fix.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update-html-data.yml
package.json

Not sure why my local environment always uses pnpm v8 for volar, and it causes pnpm-lock.yaml to be changed.

chore: specify `packageManager`

---

packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementEvents.ts
packages/typescript-plugin/lib/common.ts

Close #1894
It is not possible to generate virtual code that can display emit JSDoc. As an alternative, JSDoc is now calculated from the original type through TypeChecker and attach to the hover message via proxy getQuickInfoAtPosition.

feat(typescript-plugin): add emit JSDoc support

---

extensions/vscode/syntaxes/vue.tmLanguage.json
test-workspace/language-service/syntax/directives.vue
test-workspace/language-service/syntax/generic.vue
test-workspace/language-service/syntax/inline-style.vue
test-workspace/language-service/syntax/template-expression.vue

Partial fix #520.
Before PR:
After PR:
[An upstream fix](https://github.com/microsoft/TypeScript-TmLanguage/issues/985#issuecomment-2127996567) is ​​still required to fully resolve the issue.

fix(vscode): partial fix "as"/"instanceof" expressions syntax highlight

---

extensions/vscode/package.json
extensions/vscode/syntaxes/mdx-vue.json

This enables syntax highlighting of code blocks inside MDX files annotated with the `vue` language.

feat(vscode): enable syntax highlighting of cue code blocks in MDX

---

packages/language-core/lib/codegen/script/scriptSetup.ts

fix(language-core): use defineEmits calls instead of type infer

---

packages/component-meta/lib/base.ts
packages/language-core/lib/languageModule.ts
packages/language-server/node.ts
packages/language-service/tests/utils/createTester.ts
packages/language-service/tests/utils/format.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/index.ts

When the project does not have tsconfig, since global types will never be generated, all types in the template will be any.

fix(typescript-plugin): TS not working in template when tsconfig missing

---

packages/tsc/index.ts

This prevents that the output of a successful vue-tsc run looks the same like one finished with an unexpected error.

fix(tsc): log catched errors to console

---

packages/language-core/lib/codegen/template/element.ts

Relevant test cases: 
https://github.com/vuejs/language-tools/blob/f3f528adb0247c91ede66ae83c7add0c46db6cec/test-workspace/tsc/vue3/%233374/main.vue#L3

fix(language-core): ignore type error for possible component name

---

CHANGELOG.md

fix #3980.
The wrong links in README.md seem to have been removed.
These wrong links are caused by #3118, which performed a global replacement but missed the case of `johnsoncodehk/volar-plugins`.
btw, Volar is super nice!

docs: fix wrong links in CHANGELOG.md

---

extensions/vscode/syntaxes/vue.tmLanguage.json
test-workspace/language-service/syntax/directives.vue

fix #2550.
| Before | After |
| - | - |
| ![image](https://github.com/vuejs/language-tools/assets/63178754/daaf53a6-38e0-4718-9b3f-5606244108cb) | ![image](https://github.com/vuejs/language-tools/assets/63178754/c23d8e19-f53e-4efa-9294-75394e48ba5a) |
About the regex
```txt
(?:(?:(v-[\w-]+)(:)?)|([:\.])|(@)|(#))(?:(?:(\[)([^\]]*)(\]))|([\w-]+))?
|                         \
(?:(?:(v-[\w-]+)(:)?)|([:\.])|(@)|(#))   (?:(?:(\[)([^\]]*)(\]))|([\w-]+))?
v-a                                      <omit>                      Then, modifiers or expression
v-a:                                     [expr]
:
.
@
```

fix: directive syntax highlighting

---

package.json
packages/language-core/lib/codegen/script/globalTypes.ts
packages/language-core/lib/codegen/template/elementEvents.ts
packages/language-server/lib/hybridModeProject.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
pnpm-lock.yaml
test-workspace/package.json
test-workspace/tsc/vue3.3/env.d.ts
test-workspace/tsc/vue3.3/tsconfig.json

fix(language-core): compatible with TS 5.5

---

README.md

Hi 👋
This is a documentation update for neovim user, `nvim-cmp` is a popular neovim plugin used for auto complete code, I know this might be a little bit off topic but I hope this can help some neovim users. 
As mentioned in the content, I was inspired by [this post](https://twitter.com/youyuxi/status/1799701740000035136).
Basically this changes:
to:

docs(nvim): add nvim-cmp integration

---

extensions/vscode/package.json
package.json
packages/component-meta/package.json
packages/language-core/lib/languageModule.ts
packages/language-core/lib/plugins/vue-sfc-scripts.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-core/package.json
packages/language-plugin-pug/package.json
packages/language-server/package.json
packages/language-service/lib/plugins/vue-document-drop.ts
packages/language-service/lib/plugins/vue-sfc.ts
packages/language-service/package.json
packages/tsc/package.json
packages/typescript-plugin/package.json
pnpm-lock.yaml
tsslint.config.ts

CI runs with --frozen-lockfile which contains dependency versions that don't match with what will be installed in the end in userland because the lockfile is not shipped.
This results in tests not running on the same code as will be installed for the user, causing e.g. https://github.com/vuejs/language-tools/issues/4497

fix(vue-tsc): update required volar version

---

packages/language-service/lib/plugins/vue-sfc.ts

Typing `lang="ts"` every time when start writing a new SFC is very annoying. This PR adds completion for that.
| **Before** | ![image](https://github.com/vuejs/language-tools/assets/63178754/b29bf79d-d921-4563-9f8d-8e0ce74a6480) |
| -- | -- |
| **After** | ![image](https://github.com/vuejs/language-tools/assets/63178754/1a591b1e-23e9-47aa-b5cb-0745e0f93d80) |
**Improvements**
- Removed `!DOCTYPE` and `Custom Blocks`
- Add `script lang="ts"` and `script setup lang="ts"`
**Notes**
- The description of `script lang="ts"` is the same as `script`, and the description of `script setup lang="ts"` is the same as `script setup`. I am not sure how to update this.
- Exact matching is used in this PR. I don't know if a looser matching method should be used.
- Should the order of the completion items …

feat: better sfc-level tag name completion

---

.github/ISSUE_TEMPLATE/bug_report.yml

Some issues don't provide enough information on what is expected vs happening.

chore: add 'expected' and 'actually happening' to bug report template

---

packages/language-core/lib/codegen/script/scriptSetup.ts
test-workspace/tsc/vue2/tsconfig.json
test-workspace/tsc/vue3/#4512/main.vue
test-workspace/tsc/vue3/#4512/test1.vue
test-workspace/tsc/vue3/#4512/test2.vue
test-workspace/tsc/vue3/#4512/test3.vue

If `T` in `defineModel<T>` is not defined, try to infer from user's code.

fix(language-core): infer define model type from options type

---

extensions/vscode/syntaxes/markdown-vue.json

Motivation: https://github.com/slidevjs/slidev/pull/1743 needs to inject to `fenced_code.block.language.attributes.markdown` to support highlighting special code block attributes like 
Due to https://github.com/microsoft/vscode/issues/221682, grammar can't be injected into scopes without `patterns` and `begin`/`end`. However, only code blocks defined in [VSCode's Markdown grammar file](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json) can be overridden by injecting the same code block rules with the desired `patterns: []` into `text.html.markdown` (which has been done in [this commit](https://github.com/slidevjs/slidev/pull/1743/commits/6a20591047fb7f2ddd341e0e5e6c834cce51ff84)), so it seems that the only way to support Vue's code …

feat(vscode): add empty pattern to codeblock attributes scope

---

packages/language-server/lib/hybridModeProject.ts
packages/typescript-plugin/index.ts
packages/typescript-plugin/lib/client.ts
packages/typescript-plugin/lib/server.ts
packages/typescript-plugin/lib/utils.ts

Re-fix #4292
- Each project creates an independent named pipe instead of sharing it in a process.
- Fixed scanning of 20 indexes instead of reading `vue-tsp-table-${version}.json` intermediate file to obtain the named pipe list.
- When a new named pipe is detected, it is considered available only after completing a ping pong. This will address the issue where requests timing out during tsserver initialization cause the named pipe to be considered invalid.
- A set of requests is completed in one connection instead of multiple connections separately.

fix(typescript-plugin): improve named pipes reliability

---

packages/language-core/lib/codegen/template/interpolation.ts
test-workspace/tsc/vue3/#4604/main.vue

fix https://github.com/vuejs/language-tools/issues/4604

fix(language-core): support parse method to access ctx var in object

---

packages/language-core/lib/codegen/template/index.ts
test-workspace/tsc/vue3/#4537/main.vue

fix https://github.com/vuejs/language-tools/issues/4537

fix(language-core): escape \ and ' in className avoid type error

---

packages/language-core/lib/codegen/template/element.ts
test-workspace/language-service/syntax/namespaced.vue
test-workspace/language-service/tsconfig.json

fix #3341
| Previous | Now |
| - | - |
| ![image](https://github.com/user-attachments/assets/e58a37c5-81e4-45a1-a739-038f0472371b) | ![image](https://github.com/user-attachments/assets/2aba4b95-cc31-4a69-b9b2-c381af891e5f) |
The remaining problem is that renaming doesn't work. If you rename `C` in the script block, everything is fine. However, if `C` in `<A.B.C` is renamed to `C123`, it will become `<C123123`; if it's renamed to `D`, an error message "Rename failed to apply edits" will show.

fix: semantic highlight of the end tag of namespaced elements

---

packages/language-plugin-pug/index.ts

fix #4335.
This PR caches proxyed objects created by the Pug plugin, so that logic involving equality checking would work.
Previously, the following line doesn't remove `v-for` node because every time `node.props` generates a different array.
https://github.com/vuejs/language-tools/blob/9ef235b3cabe1639c3e048bcf347c76575ecb09f/packages/language-core/lib/codegen/template/templateChild.ts#L138
| Prev | ![image](https://github.com/user-attachments/assets/acbda20a-eb65-4991-8774-bf887c11660b) |
| - | - |
| **Now** | ![image](https://github.com/user-attachments/assets/68db5d73-0186-4d8d-99af-d5f6636fbbaf) |

fix(language-plugin-pug): should cache proxyed object

---

packages/language-core/lib/codegen/script/scriptSetup.ts
test-workspace/tsc/vue2/tsconfig.json
test-workspace/tsc/vue3/#4646/child.vue
test-workspace/tsc/vue3/#4646/child2.vue
test-workspace/tsc/vue3/#4646/parent.vue

fix(language-core): nullable modelvalues

---

packages/language-core/lib/codegen/script/globalTypes.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/objectProperty.ts
test-workspace/tsc/vue3/#4668/child.vue
test-workspace/tsc/vue3/#4668/main.vue

fix #4668.
Introduced a new helper:
```ts
function __VLS_tryAsConstant<const T>(t: T): T;
```
which is used to infer the type of an arbitrary expression like `as const`, but not throwing errors when this can't be done. For example, `("1" + "2") as const` will be an error, but `__VLS_tryAsConstant("1" + "2")` will just be of type `string`.
btw, I think `__VLS_tryAsConstant` can be used in other places to provide more precise type info - but it may cause performance issues.

fix: should try casting dynamic slot name into constant

---

packages/typescript-plugin/lib/server.ts

This one ensures that
```typescript
console.warn('[Vue Named Pipe Server] Unknown request type:', request.type);
```
is not falsely executed for existing request types.

fix(typescript-plugin): unknown request type warning

---

packages/language-service/lib/plugins/vue-sfc.ts

fix(language-service): consistent data from provider for sfc completion

---

packages/language-core/lib/codegen/template/element.ts

fix(language-core): drop duplicate hints on incomplete tag

---

packages/language-core/lib/codegen/template/elementProps.ts
packages/language-server/tests/inlayHints.spec.ts

fix(language-core): correct inlay hints for v-bind with modifier

---

packages/language-core/lib/codegen/script/component.ts
test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs_unknownTag/basic.vue
test-workspace/tsc/passedFixtures/vue3_strictTemplate/inheritAttrs_unknownTag/main.vue

When the root tag type is unknown and the component missing props define, the component type is corrupted. This is actually defineComponent's bug and trying to avoid it on our side.
Related: https://github.com/vuejs/core/pull/7419

fix(language-core): fallthrough attributes break component type when root tag type is unknown

---

packages/language-core/lib/codegen/script/component.ts
packages/language-core/lib/codegen/script/globalTypes.ts
packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/codegen/script/internalComponent.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/index.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap

Re-fix #4391, also solves the problem of defineComponent type calculation being too deep when `fallthroughAttributes` is enabled.

refactor(language-core): do not wrap template virtual code with function

---

packages/language-core/lib/plugins/file-md.ts

fix(language-core): transform range of `file-md` correctly

---

packages/language-core/lib/codegen/script/index.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/index.ts

fix #4737, fix #4738, fix #4739
https://github.com/vuejs/core/blob/8c3fdd1a7d4060680f8379fac8848d9f5f6e5620/packages/vue/package.json#L69

fix: write globalTypes into `dist` for correct export

---

packages/component-meta/lib/base.ts
packages/language-core/lib/codegen/script/index.ts
packages/language-server/lib/initialize.ts
packages/tsc/index.ts
packages/tsc/tests/dts.spec.ts
packages/typescript-plugin/index.ts

fix: apply snake case on globalTypes filename

---

.github/ISSUE_TEMPLATE/bug_report.yml

Many issues are caused by third-party extensions. It might be good to let our users post their list of dependencies. Optional for now (?)

chore: Add optional "dependencies" textarea to issue template [ci skip]

---

extensions/vscode/src/common.ts

The Microsoft AL Language Extension for Microsoft Dynamics 365 Business shows up as potentially incompatible when starting VS Code and opening .vue files. These are unrelated to to the AL language plugin. 
Changing hybrid mode to true does not cause any interference with Vue files as far as I can tell.

fix: Whitelist ms-dynamics-smb.al extension for Vue Hybrid Mode.

---

extensions/vscode/syntaxes/vue.tmLanguage.json
extensions/vscode/tests/__snapshots__/grammar.spec.ts.snap
extensions/vscode/tests/grammarFixtures/tag-starts-with-template.vue

fix(vscode): correct highlighting on tag starting with `template`

---

packages/language-core/lib/plugins/vue-template-html.ts
packages/language-core/lib/utils/parseSfc.ts

fix(language-core): auto-completion for the last line of template block

---

packages/language-core/lib/codegen/template/elementEvents.ts
packages/language-core/lib/codegen/template/elementProps.ts

pref: don't emit event lnlayhint when content is none

---

packages/language-core/lib/codegen/globalTypes.ts

related to twoslashes/twoslash#51

fix(language-core): ensure to pass tsc on inline global types

---

packages/language-core/lib/codegen/globalTypes.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/elementDirectives.ts
packages/language-core/lib/parsers/scriptRanges.ts
test-workspace/tsc/passedFixtures/vue2/tsconfig.json
test-workspace/tsc/passedFixtures/vue3/directives/main.vue
test-workspace/tsc/passedFixtures/vue3/directives/option.vue

feat(language-core): typed directives in template

---

packages/language-core/lib/codegen/common.ts
packages/language-core/lib/codegen/script/componentSelf.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/index.ts
packages/language-core/lib/codegen/template/interpolation.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-service/lib/plugins/vue-inlayhints.ts
test-workspace/tsc/passedFixtures/vue2/tsconfig.json
test-workspace/tsc/passedFixtures/vue3.4/tsconfig.json
test-workspace/tsc/passedFixtures/vue3/#4820/main.vue

fix(language-core): avoid generic type loss due to destructured props

---

packages/language-core/lib/codegen/template/templateChild.ts
packages/language-core/lib/codegen/template/vFor.ts
test-workspace/tsc/passedFixtures/vue3/#4827/child.vue
test-workspace/tsc/passedFixtures/vue3/#4827/main.vue

fix(language-core): handle `v-for` with `v-once` correctly

---

packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/script/template.ts
test-workspace/tsc/passedFixtures/vue3/#4841/main.vue

fix(language-core): don't assign `this` to `__VLS_ctx`

---

packages/language-server/tests/inlayHints.spec.ts
packages/language-service/lib/plugins/vue-inlayhints.ts

Prevent mistakenly identifying properties such as `toString` inherited from `Object` as props.

fix(language-service): initialize scope with null prototype object

---

README.md

I noticed a mistake in the snippet for nvim, there was a missing `}` and a trailing.

chore: fix nvim config snippet in README

---

test-workspace/tsc/passedFixtures/vue3/defineProp_A/script-setup.vue

In https://github.com/vuejs/core/pull/12227, I attempted to fix the `default` type restriction in `PropOptions`, but it caused CI failures (https://github.com/vuejs/ecosystem-ci/actions/runs/11435154446/job/31810009674).
Previously, `default` allowed arbitrary objects, leading to incorrect tests passing.

test: fix incorrect default value

---

packages/component-meta/package.json
packages/component-type-helpers/package.json
packages/language-core/package.json
packages/language-plugin-pug/package.json
packages/language-server/package.json
packages/language-service/package.json
packages/tsc/package.json
packages/typescript-plugin/package.json

This would allow bundlers to tree shake the module code when imports are not done via `import type`.
E.g., 
```ts
import { ComponentProps } from 'vue-component-type-helpers';
```
Also, I would like to know why the `code` needs to be default exported as a string containing the same TS code again. Is it maybe some artifact from the past and or only relevant to Vue2?

chore: remove side effects

---

packages/language-core/lib/codegen/template/elementProps.ts
test-workspace/tsc/passedFixtures/vue3/#4862/main.vue

fix(language-core): generate correct reference for `v-on` on `<slot>`

---

packages/language-core/lib/utils/parseCssClassNames.ts
packages/language-core/lib/utils/parseCssVars.ts

To match selectors like `:has(.checked)`.
For languages ​​like scss or less that have `{ }` and `;` syntax, try to exclude the content between `{` and `;` to reduce the false matching rate.

fix(language-core): match classname before `)`

---

packages/language-service/lib/plugins/vue-template.ts

fix(language-service): handle internal item key with leading slash correctly

---

packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/types.ts
packages/language-core/lib/utils/ts.ts
packages/tsc/tests/dts.spec.ts

fix https://github.com/vuejs/language-tools/issues/4860
Check the detail info here
https://github.com/vuejs/language-tools/issues/4860#issuecomment-2406554626
Change globalTypes reference to absolute path:
before: 
``` ts
/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
```
after:
```ts
/// <reference types="/absolute/path/to/.vue-global-types/vue_3.4_false.d.ts" />
```

fix(language-core): refer absolute path of global types file

---

packages/component-meta/lib/base.ts

In certain cases, `signatures[0].parameters[0]` returns undefined. We need to prevent this from causing an error.

fix(component-meta): error when signatures is undefined

---

packages/language-core/lib/codegen/script/scriptSetup.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/tsc/passedFixtures/vue3/#4890/main.vue

fix(language-core): generate `value` instead of model name into tuple

---

packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/templateChild.ts
packages/language-core/lib/codegen/template/vFor.ts
test-workspace/tsc/passedFixtures/vue3/templateRef/template-ref.vue

fix(language-core): infer template ref's type of native elements with `v-for` correctly

---

packages/language-core/lib/codegen/script/componentSelf.ts
packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/plugins/vue-tsx.ts

This is an alternative to avoid the bug in #4963.
The root cause of #4963 is still unclear and will be clarified before merging.

fix(language-core): reference global types file with relative path

---

extensions/vscode/syntaxes/vue.tmLanguage.json
packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementDirectives.ts
packages/language-core/lib/codegen/template/templateChild.ts
packages/language-core/lib/plugins/vue-template-inline-ts.ts
packages/language-service/lib/plugins/vue-directive-comments.ts
test-workspace/tsc/passedFixtures/vue2/tsconfig.json
test-workspace/tsc/passedFixtures/vue3/v-generic/comp.vue
test-workspace/tsc/passedFixtures/vue3/v-generic/main.vue

feat(language-core): support `@vue-generic`

---

packages/component-meta/tests/index.spec.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/tsc/passedFixtures/vue3/#4978/comp.vue
test-workspace/tsc/passedFixtures/vue3/#4978/main.vue

This pull request includes changes to improve the handling of component property modifiers in the `generateComponentProps` function and its associated tests.
It aims to better reflect `modelModifiers` type marking keys as optional:
```html
<script setup lang="ts">
const [modelValue, modelModifiers] = defineModel<string, 'foo' | 'bar'>()
// modelModifiers.foo?: true
// modelModifiers.bar?: true
</script>
```
With this update, we can omit keys when manually defining `model-modifiers` prop
```html
<template>
<MyComp :model-modifiers="{ foo: true }" />
</template>
```
Note that it will also fix type when using `vitest` and `@vue/test-utils`:
```ts
import { MyComp } from './MyComp.vue'
import { mount } from '@vue/test-utils'
import { it } from 'vitest'
it('should foo modifier', async () => { …
```

fix(language-core): make model modifiers optional

---

packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementProps.ts
packages/language-core/lib/codegen/template/slotOutlet.ts
test-workspace/tsc/passedFixtures/vue3/#4979/main.vue

fix(language-core): always report missing props on `<slot>`

---

README.md

2 months ago nvim-lspconfig [update](https://newreleases.io/project/github/neovim/nvim-lspconfig/release/v1.0.0) resulted in `tsserver` renamed to `ts_ls`. Current docs doesn't reflect changes so I replaced matches and provided info link.

docs: update nvim guide

---

extensions/vscode/package.json
pnpm-lock.yaml

`reactive-vscode@0.2.7-beta.1` contains a critical bug which stops the extension from watching config changes

chore: upgrade `reactive-vscode` to v0.2.7

---

packages/language-core/lib/parsers/scriptSetupRanges.ts
test-workspace/tsc/passedFixtures/vue3/#5027/main.vue

fix(language-core): avoid unchecked index access when parsing `defineEmits`

---

packages/language-core/lib/codegen/template/element.ts

fix(language-core): don't generate variable access of template refs using `useTemplateRef`

---

packages/language-core/lib/codegen/script/componentSelf.ts
packages/language-core/lib/codegen/script/context.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-service/lib/plugins/vue-template.ts

```ts
import { default as Comp } from './Comp.vue';
//                  ^^^^
```

fix(language-core): handle named default import of components correctly

---

packages/language-server/lib/hybridModeProject.ts
packages/language-service/lib/plugins/vue-template.ts
packages/typescript-plugin/lib/client.ts
packages/typescript-plugin/lib/requests/componentInfos.ts
packages/typescript-plugin/lib/server.ts
packages/typescript-plugin/lib/utils.ts

perf(typescript-plugin): use named pipe servers more efficiently

---

packages/language-core/lib/codegen/template/elementEvents.ts
packages/language-core/lib/codegen/template/elementProps.ts
packages/language-service/lib/plugins/vue-template.ts

```vue
<template>
<Comp @vue:mounted="..." />
</template>
```

fix(language-core): correct type and completion support of `vue:` event

---

packages/language-service/lib/ideFeatures/nameCasing.ts
packages/language-service/lib/plugins/vue-autoinsert-dotvalue.ts
packages/language-service/lib/plugins/vue-complete-define-assignment.ts
packages/language-service/lib/plugins/vue-document-drop.ts
packages/language-service/lib/plugins/vue-document-links.ts
packages/language-service/lib/plugins/vue-extract-file.ts
packages/language-service/lib/plugins/vue-inlayhints.ts
packages/language-service/lib/plugins/vue-sfc.ts
packages/language-service/lib/plugins/vue-template.ts
packages/language-service/lib/plugins/vue-twoslash-queries.ts
packages/typescript-plugin/lib/common.ts
packages/typescript-plugin/lib/requests/collectExtractProps.ts

Adopt the following naming and logic as much as possible:
```ts
const uri = URI.parse(document.uri);
const decoded = context.decodeEmbeddedDocumentUri(uri);
const sourceScript = decoded && context.language.scripts.get(decoded[0]);
const virtualCode = decoded && sourceScript?.generated?.embeddedCodes.get(decoded[1]);
if (!sourceScript?.generated || virtualCode?.id !== '...') {
return;
}
const root = sourceScript.generated.root;
if (!(root instanceof VueVirtualCode)) {
return;
}
```

refactor(language-service): consistent style of source and virtual code operation

---

extensions/vscode/package.json

feat(vscode): add examples to inlay hints configuration

---

packages/language-core/lib/parsers/scriptSetupRanges.ts
test-workspace/tsc/passedFixtures/vue3/templateRef/main.vue

`useTemplateRef` and `useCssModule` using in function maybe have a different instance.
In addition [jsx-macros](https://github.com/vue-macros/vue-macros/pull/794) can using in vue-sfc .

fix(language-core): prevent visiting functional components for parseScriptSetupRanges

---

packages/language-core/lib/codegen/script/scriptSetup.ts

https://github.com/twoslashes/twoslash/pull/62

fix(language-core): ignore ts errors in function-scoped declare expressions

---

packages/language-core/lib/codegen/globalTypes.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/index.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-server/tests/completions.spec.ts
packages/typescript-plugin/lib/requests/componentInfos.ts
test-workspace/tsc/passedFixtures/vue3/#5097/child.ts
test-workspace/tsc/passedFixtures/vue3/#5097/child.vue
test-workspace/tsc/passedFixtures/vue3/#5097/main.vue

fix(language-core, typescript-plugin): handle self-reference component correctly

---

packages/language-service/lib/plugins/vue-extract-file.ts

fix(language-service): set code action kinds to avoid warning

---

packages/language-service/lib/plugins/vue-template.ts
packages/typescript-plugin/lib/requests/componentInfos.ts
packages/typescript-plugin/lib/server.ts
packages/typescript-plugin/lib/utils.ts

feat(language-service): display deprecated info of props in completion

---

packages/language-core/lib/codegen/template/interpolation.ts
test-workspace/tsc/passedFixtures/vue3/#5157/main.vue

fix(language-core): map interpolation error with multiple variables correctly

---

extensions/vscode/src/languageClient.ts

Applying the config only needs to reload the extension host. If reloading the window, terminal session and many other things will be lost.

chore: ask user to reload extension host when configuration changes

---

packages/language-core/lib/codegen/script/scriptSetup.ts
test-workspace/tsc/passedFixtures/vue3.4/defineModel/main.vue
test-workspace/tsc/passedFixtures/vue3/defineModel/main.vue

fix(language-core): add `undefined` to first param type of optional model emits

---

packages/language-core/lib/codegen/template/index.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/component-meta/generic/component.vue
test-workspace/component-meta/generic/custom-extension-component.cext
test-workspace/component-meta/template-slots/component-define-slots.vue
test-workspace/tsc/passedFixtures/#2472/generic.vue
test-workspace/tsc/passedFixtures/vue3.4/components/main.vue
test-workspace/tsc/passedFixtures/vue3.4/components/script-setup-generic.vue
test-workspace/tsc/passedFixtures/vue3/#3371/main.vue
test-workspace/tsc/passedFixtures/vue3/#3561/child.vue
test-workspace/tsc/passedFixtures/vue3/#3671/main.vue
test-workspace/tsc/passedFixtures/vue3/#4263/main.vue
test-workspace/tsc/passedFixtures/vue3/#4327/main.vue
test-workspace/tsc/passedFixtures/vue3/#4979/main.vue
test-workspace/tsc/passedFixtures/vue3/components/main.vue
test-workspace/tsc/passedFixtures/vue3/components/script-setup-generic.vue
test-workspace/tsc/passedFixtures/vue3/slots/main.vue
test-workspace/tsc/passedFixtures/vue3_strictTemplate/#2726/main.vue

Reference https://typescript-eslint.io/rules/method-signature-style.
It will allow us to perform more strict type checks on slots.

refactor(language-core): generate the type of slots with function property

---

packages/language-core/lib/codegen/codeFeatures.ts
packages/language-core/lib/codegen/script/component.ts
packages/language-core/lib/codegen/script/componentSelf.ts
packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/script/src.ts
packages/language-core/lib/codegen/script/styleModulesType.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementDirectives.ts
packages/language-core/lib/codegen/template/elementEvents.ts
packages/language-core/lib/codegen/template/elementProps.ts

- Extract code features to share between the codegen of script and template.
- Use `resolveCodeFeatures` in the template codegen to ensure that all code info with verification enabled is converted by it, preventing `@vue-expect-error` from being invalid on certain mappings.

refactor(language-core): more robust code features resolution

---

packages/language-core/lib/codegen/script/component.ts

If defineComponent's options don't end with a comma, it will cause a TS 1005 error.

fix(language-core): move generateSfcBlockSection to the end to fix missing comma errors

---

packages/language-core/lib/codegen/template/index.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/language-core/lib/plugins/vue-tsx.ts

fix(language-core): use return values of `useSlots` and `useAttrs` directly in the template

---

packages/language-core/lib/codegen/template/templateChild.ts
packages/language-core/lib/plugins/vue-template-inline-ts.ts

chore(language-core): adjust regex match for @vue-generic comments to improve offset calculation

---

packages/language-core/lib/plugins/file-md.ts

fix(language-core): ignore latex block content

---

packages/language-core/lib/codegen/script/component.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/index.ts
packages/language-core/lib/codegen/template/interpolation.ts
packages/language-core/lib/plugins/file-md.ts
packages/language-core/lib/types.ts
packages/language-core/lib/utils/ts.ts
packages/language-core/schemas/vue-tsconfig.schema.json
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/tsc/passedFixtures/vue3/rootEl/base.vue
test-workspace/tsc/passedFixtures/vue3/rootEl/child.vue
test-workspace/tsc/passedFixtures/vue3/rootEl/main.vue
test-workspace/tsc/passedFixtures/vue3/slots/main.vue
test-workspace/tsc/passedFixtures/vue3/templateRef/main.vue
test-workspace/tsc/passedFixtures/vue3/templateRef/template-refs.vue

close #5116, close #5183, close #5197, fix #5128
```json
{
"inferComponentDollarEl": {
"type": "boolean",
"default": false,
"markdownDescription": "Infer `$el` type on the component instance."
},
"inferComponentDollarRefs": {
"type": "boolean",
"default": false,
"markdownDescription": "Infer `$refs` type on the component instance."
},
"inferTemplateDollarAttrs": {
"type": "boolean",
"default": false,
"markdownDescription": "Infer `$attrs` type in the template and the return type of `useAttrs`."
},
"inferTemplateDollarEl": {
"type": "boolean",
"default": false,
"markdownDescription": "Infer `$el` type in the template."
},
"inferTemplateDollarRefs": {
"type": "boolean",
"default": false,
"markdownDescription": "Infer `$refs` type in the template."
},
"inferTemplateDollarSlots": {
"type": …
```

feat(language-core): introduce options to control type inference of `$attrs`, `$el`, `$refs` and `$slots`

---

packages/language-core/lib/codegen/script/scriptSetup.ts

https://github.com/vuejs/core/issues/12817#issuecomment-2669056595

fix(language-core): do not emit undefined for model with falsy default value

---

packages/component-meta/lib/base.ts
packages/component-meta/tests/index.spec.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/component-meta/reference-type-model/component.vue

fix(component-meta): resolve `defineModel` options to collect `default` value

---

packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/elementEvents.ts
test-workspace/tsc/passedFixtures/vue2/tsconfig.json
test-workspace/tsc/passedFixtures/vue3/#5225/comp.vue
test-workspace/tsc/passedFixtures/vue3/#5225/main.vue

fix(language-core): generate condition guards for model events

---

packages/language-core/lib/codegen/globalTypes.ts
packages/language-core/lib/codegen/template/index.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/tsc/passedFixtures/vue3/slots/main.vue

fix #5232 
Due to the above limitations, we will not intersect `$slots` with slot types declared by option api now.

fix(language-core): prevent global types generation in declaration files

---

packages/language-core/lib/codegen/globalTypes.ts
test-workspace/tsc/passedFixtures/vue3/#5228/main.vue

fix(language-core): prevent eager inference of slot props from generics

---

packages/language-core/lib/codegen/template/elementProps.ts
test-workspace/tsc/passedFixtures/vue3/#5262/comp.vue
test-workspace/tsc/passedFixtures/vue3/#5262/main.vue

fix(language-core): correct error mapping when prop exp is arrow function

---

packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/index.ts
test-workspace/tsc/passedFixtures/vue3/templateRef/template-refs.vue

fix(language-core): correct type inference of multiple template refs with same name

---

packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts

fix(language-core): do not drop leading comments of `defineModels`

---

packages/language-core/lib/codegen/globalTypes.ts
packages/language-core/lib/codegen/template/vSlot.ts

fix(language-core): transform slot parameter list into equivalent binding pattern

---

packages/typescript-plugin/lib/requests/utils.ts
packages/typescript-plugin/package.json
pnpm-lock.yaml

fix(typescript-plugin): use `path-browserify` instead of `node:path`

---

.github/workflows/auto-fix.yml
packages/language-core/index.ts

By default, `pull_request_target` checks out the main branch of vuejs/language-tools and runs the auto fix there. This is very likely not what you wanted to achive.
Also, the permissions pull_request_target has are very broad and can be dangerous.

fix(ci): Run auto-fix from the correct branch

---

.github/workflows/auto-fix.yml
packages/language-service/lib/plugins/vue-template.ts
packages/typescript-plugin/lib/requests/getComponentProps.ts

| from | to |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/6e0b4aa7-1c52-479a-b68e-78d53f98111e) | ![image](https://github.com/user-attachments/assets/1f169641-7bb9-42ec-8f48-adc4b4c56c15) |

feat(language-service): set the kind of props inherited from intrinsic elements to `Value` instead of `Field`

---

.gitignore
packages/component-meta/lib/base.ts
packages/component-meta/package.json
packages/language-core/lib/codegen/script/componentSelf.ts
packages/language-core/lib/codegen/script/index.ts
packages/language-core/lib/plugins/vue-tsx.ts
packages/language-core/lib/utils/ts.ts
packages/language-core/package.json
packages/language-service/lib/plugins/vue-document-drop.ts
packages/language-service/package.json
packages/typescript-plugin/lib/requests/utils.ts
packages/typescript-plugin/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Stumbling across https://github.com/vuejs/language-tools/pull/5304 I saw that `path-browserify` could be replaced by unjs `pathe`. `path-browserify` has not been updated for 5 years, is only commonjs and from its docs `path-browserify currently matches the Node.js 10.3 API.
I used pnpm catalog to synchronise versions across the monorepo. We can replace this with the current version if needed.
We can even think about replacing `node:path` with `pathe` too.
All vitest tests pass.
If this PR is accepted, I can open a backport to v2.

chore(deps): replace `path-browserify` with `pathe`

---

packages/language-core/lib/codegen/template/elementDirectives.ts
packages/language-core/lib/codegen/template/elementProps.ts
packages/language-core/lib/codegen/template/slotOutlet.ts

| ts | before | after |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/d987ade7-1f07-4980-b84b-d6ebe39db4b3) | ![image](https://github.com/user-attachments/assets/14e03b79-12d3-4b59-9e44-58a7001e8d72) | ![image](https://github.com/user-attachments/assets/47fdb5f9-1c55-463d-966f-006b14d669e1) |

fix(language-core): remove semantic highlight of v-bind shorthand

---

extensions/vscode/syntaxes/vue.tmLanguage.json
extensions/vscode/tests/__snapshots__/grammar.spec.ts.snap

Resolve the Linguist reference issue by inlining html comment pattern. The snapshot is also updated with similar referencing issues.
#5026 will be resolved once this is merged and the next Linguist release (in a few months) is deployed.

fix: inline html comment pattern in Vue syntax definition

---

extensions/vscode/package.json
packages/component-meta/package.json
packages/language-core/package.json
packages/language-plugin-pug/package.json
packages/language-server/package.json
packages/language-service/package.json
packages/tsc/package.json
packages/typescript-plugin/package.json
pnpm-lock.yaml

Patch versions of Volar are known to create incompatibilities with Vue Language Tools. This change fixes this problem for the @vue/language-server package downloaded from the npm registry.
For example something here https://github.com/volarjs/volar.js/compare/v2.4.11...v2.4.12 breaks Vue Language Server 2.2.8, and npm will download the latest patch release of dependency. This doesn't show up in VSCode Extension, because Volar 2.4.11 was specified in pnpm-lock of vue-language-tools monorepo, but as far as I know it might affect all other editors.
Next I'd create similar PR for `v2` branch.

fix: depend on exact volar version

---

extensions/vscode/package.json
packages/component-meta/package.json
packages/language-core/package.json
packages/language-plugin-pug/package.json
packages/language-server/package.json
packages/language-service/package.json
packages/tsc/package.json
packages/typescript-plugin/package.json
pnpm-lock.yaml

Patch versions of Volar are known to create incompatibilities with Vue Language Tools. This change fixes this problem for the @vue/language-server package downloaded from the npm registry.
For example something here https://github.com/volarjs/volar.js/compare/v2.4.11...v2.4.12 breaks Vue Language Server 2.2.8, and npm will download the latest patch release of dependency. This doesn't show up in VSCode Extension, because Volar 2.4.11 was specified in pnpm-lock of vue-language-tools monorepo, but as far as I know it might affect all other editors.

fix: depend on exact volar version [v2]

---

packages/component-meta/lib/base.ts

fix(component-meta): only exclude vnode events from props

---

extensions/vscode/package.json

Remove Vite problem matcher that added in #1320. We should recommend VSCode to have a built-in Vite problem matcher instead.

refactor(vscode): remove Vite problem matcher

---

README.md

`Volar` package name in Mason registry has changed to `vue_ls` in latest, see commit history https://github.com/mason-org/mason-registry/tree/main/packages/vue-language-server

chore(docs): update vue language package name

---

README.md

I couldn't make the vue_language_server work in my nvim setup, I may have an issue related with the order my plugins are loading because I simply can't get the variable $MASON in my lspconfig setup file, but I do have it right when I run `:echo $MASON` from nvim command mode. Anyway, this is the approach that works for me, I guess it's worth it to also mention it to users as an alternative. I haven't used vuejs ever since I got this issue just because I couldn't make it work.

chore(docs): vue_language_server_path in nvim setup example

---

extensions/vscode/syntaxes/vue.tmLanguage.json

fix(vscode): correct syntax highlight for directives starting with `v-for`

---

packages/language-core/lib/plugins.ts
packages/language-core/lib/utils/ts.ts

The line below returns a nested array of plugins, so use flat() to handle it.
https://github.com/vuejs/language-tools/blob/b4ac06071bcfc0aa011fc5c9cfa09578a3fb0b18/packages/language-core/lib/utils/ts.ts#L194

fix(language-core): flatten plugins

---

extensions/vscode/rolldown.config.ts
extensions/vscode/src/languageClient.ts
packages/language-server/lib/types.ts
packages/language-server/node.ts
packages/language-server/package.json
packages/language-server/tests/server.ts
pnpm-lock.yaml

In v3, the Vue language server no longer provides TS semantic functionality, and the configurable TSDK version no longer makes sense. Changing typescript to a peer dependency will simplify all IDE integrations.

refactor(language-server): drop `typescript.tsdk` initialization option

---

packages/tsc/tests/typecheck.spec.ts
pnpm-lock.yaml
test-workspace/package.json

We tried adding typescript@next to CI tests to catch regressions in future TS versions in advance, but in real experience this approach never really helped us find regressions, and we should remove it to speed up testing time and look for other more suitable approaches.

test(tsc): remove typescript-next test

---

packages/language-core/lib/codegen/style/imports.ts
packages/language-core/lib/codegen/style/modules.ts
packages/language-core/lib/codegen/style/scopedClasses.ts
packages/language-core/lib/types.ts
packages/language-core/lib/utils/ts.ts
packages/language-core/schemas/vue-tsconfig.schema.json
packages/language-service/lib/plugins/vue-document-links.ts
test-workspace/tsc/passedFixtures/#5136/tsconfig.json
test-workspace/tsc/passedFixtures/vue3/#3688/main.vue

| from | to |
| --- | --- |
| `resolveExternalStylesheets` | `resolveStyleImports` |
| `experimentalResolveStyleCssClasses` | `resolveStyleClassNames` |

refactor(language-core): rename style related configurations for consistency

---

extensions/vscode/lib/splitEditors.ts
packages/language-core/lib/parsers/scriptSetupRanges.ts
packages/language-server/index.ts
packages/language-server/lib/reactionsAnalyze.ts
packages/language-server/lib/reactionsAnalyzeLS.ts
packages/language-service/index.ts

Move in the server code of Insiders edition features to allow integration with IDEs other than VSCode.
The current code is not neat and needs to be refactored in the next PR.

refactor(language-server): move in server code from insiders edition

---

packages/language-core/lib/codegen/codeFeatures.ts
packages/language-core/lib/codegen/script/scriptSetup.ts
packages/language-core/lib/codegen/script/template.ts
packages/language-core/lib/codegen/template/context.ts
packages/language-core/lib/codegen/template/element.ts
packages/language-core/lib/codegen/template/elementDirectives.ts
packages/language-core/lib/codegen/template/elementEvents.ts
packages/language-core/lib/codegen/template/elementProps.ts
packages/language-core/lib/codegen/template/index.ts
packages/language-core/lib/codegen/template/interpolation.ts
packages/language-core/lib/codegen/template/objectProperty.ts
packages/language-core/lib/codegen/template/propertyAccess.ts
packages/language-core/lib/codegen/template/slotOutlet.ts
packages/language-core/lib/codegen/template/templateChild.ts
packages/language-core/lib/codegen/template/vFor.ts
packages/language-core/lib/codegen/template/vIf.ts
packages/language-core/lib/codegen/template/vSlot.ts
packages/language-core/lib/codegen/utils/index.ts
packages/language-core/lib/plugins/vue-template-inline-ts.ts
packages/language-core/lib/virtualFile/computedSfc.ts

Originally, we held the inline TS ASTs within their respective attribute nodes. While this approach allowed them to persist during incremental updates of the template, when edits break the template structure and triggered a fallback to full updates, all inline TS would be re-parsed—even if their content remained entirely unchanged.  
Now, we held these inline TS ASTs in a `Map` property of the template AST and perform cache checks when recomputing the template AST. This change brings two key benefits:  
1. Most inline TS ASTs will be reused during full updates.
2. Inline TS with same content will share the same AST.

perf(language-core): cache and reuse inline ts asts during full updates

---

packages/language-core/lib/codegen/globalTypes.ts
packages/language-core/lib/codegen/localTypes.ts
packages/tsc/tests/__snapshots__/dts.spec.ts.snap
test-workspace/tsc/passedFixtures/vue3/#5159/child.vue
test-workspace/tsc/passedFixtures/vue3/#5159/main.vue

fix(language-core): `Prettify<T>` breaks generics inferencing

---

packages/language-server/index.ts
packages/language-service/lib/plugins/vue-twoslash-queries.ts

fix(language-service): correct position calculation of twoslash queries

---

packages/tsc/index.ts

Hello, I tried to find a way to use `vue-tsc` programmatically to pass it into tools like `webpack/rspack-ts-checker`, but it is currently designed to simply invoke only `tsc` cli.
This PR in combination with [a same change on `volar` side](https://github.com/volarjs/volar.js/pull/279) will allow to make use of not just `lib/tsc`, but also `lib/typescript` and pass it to any tool that expects the typescript API as simply as
```js
// vue-typescript.js
module.exports = require('vue-tsc').runTsc(require.resolve('typescript'))
```
```js
...
someCheckerPlugin({
typescript: require.resolve('./vue-typescript')
})
...
```

refactor(tsc): return the result of runTsc

---

packages/language-core/lib/codegen/script/scriptSetup.ts

fix(language-core): generate `modelModifiers` for explicitly declared default model name

---

packages/language-service/lib/plugins/vue-global-types-error.ts

Improved the global types error message to be more inclusive and helpful for both JavaScript and TypeScript projects.
- **Enhanced error message**: Changed from "tsconfig.json" to "tsconfig.json or jsconfig.json" to support JavaScript projects
- **Added performance guidance**: Included recommendation to add `"exclude": ["node_modules"]` when creating new config files to maintain VS Code performance
- **Better user experience**: More comprehensive guidance for developers working with both JS and TS projects
When users are in a non-npm like environment, they may be missing both the node_modules directory and TypeScript/JavaScript configuration files. The previous error message only mentioned `tsconfig.json`, which could confuse JavaScript developers who use `jsconfig.json`.
More …

chore(language-service): improve global types error message for JS projects

---

packages/language-core/lib/utils/ts.ts

When `rootDir` is passed as `/`, the default value of `configFileName` is simply concatenated into an invalid `//jsconfig.json`, which causes the TS `parseJsonConfigFileContent` method to perform file searches with incorrect parameters, coincidentally making it impossible to reproduce issue #5598 in posix path systems.
After this PR, I was able to reproduce #5598 on OSX.
It should be noted that for files not included in the tsconfig, `rootDir` should fall back to the workspace root directory rather than `/`, which requires investigation in VSCode.

fix(language-core): remove the non-strict `configFileName` default value

---

packages/language-core/lib/codegen/template/interpolation.ts
packages/language-core/lib/codegen/template/vSlot.ts
test-workspace/tsc/passedFixtures/vue3/#5617/main.vue

fix(language-core): generate slot parameters in the same way as interpolation

---

packages/language-service/lib/plugins/typescript-semantic-tokens.ts
packages/language-service/lib/plugins/vue-document-highlights.ts

fix(language-service): do not provide semantic tokens and document highlights for non-`file` scheme files

---

packages/language-core/lib/codegen/template/element.ts
test-workspace/tsc/passedFixtures/fallthroughAttributes_strictTemplate/generic/basic.vue
test-workspace/tsc/passedFixtures/fallthroughAttributes_strictTemplate/generic/child.vue
test-workspace/tsc/passedFixtures/fallthroughAttributes_strictTemplate/generic/main.vue

fix(language-core): use component instance props as fallthrough attributes
