packages/vscode-server/src/languageServiceHost.ts
I think the message can have markdown but I am not sure.
=> chore: improve warning message

packages/vscode-vue-languageservice/src/services/completion.ts
Before:
https://user-images.githubusercontent.com/17216317/115713186-4dcc4d00-a3a8-11eb-9751-928f8bb3b068.mp4
After:
https://user-images.githubusercontent.com/17216317/115713221-5886e200-a3a8-11eb-87cf-a809ddaa3c60.mp4
=> fix: don't complete attribute value for `v-else`

README.md
I'm not a native speaker but highly confident that this PR improves the readme's grammar. I also added a few links where I think it's helpful.
=> docs: slightly improved README grammar & added links

packages/vscode-typescript-languageservice/src/services/completion.ts, packages/vscode-typescript-languageservice/src/services/completionResolve.ts, packages/vscode-vue-languageservice/src/services/completionResolve.ts
✅ Closes: #198
details lost extension after resolved by ts-service, only happend when resolve `tsx` and ts
after this pr: 
https://user-images.githubusercontent.com/17974631/119636543-52709f00-be47-11eb-82c1-d538afc9cc93.mp4
=> fix: 🐛 https://github.com/johnsoncodehk/volar/issues/198

package.json
=> feat: 🎸 resolved #195

.github/test.yml
add github-action, avoid contributor to introduce regression
=> ci: 🎡 add github-action

packages/vscode-vue-languageservice/src/sourceFile.ts, packages/vscode-vue-languageservice/src/types.ts, packages/vscode-vue-languageservice/src/use/useSfcStyles.ts, packages/vscode-vue-languageservice/src/use/useSfcTemplateScript.ts, packages/vscode-vue-languageservice/src/utils/sourceMaps.ts
There doesn't seem to be existing tests, so none was added. I don't know how to test with a dev extension yet so this might not work.
Only saw the rewrite warning after finishing the PR 😂  Well, hope it at least serves as a reminder for this feature
=> feat: support sfc named css modules

packages/vscode-typescript-languageservice/src/index.ts, packages/vscode-typescript-languageservice/src/utils/previewer.ts, yarn.lock
https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/utils/previewer.ts#L170
=> chore: sync previewer.ts with vscode

README.md
Description
-------------------------------------------------------
There is an LSP client plugin called `vim-lsp` for Vim8/Neovim.
Thank you for adjusting the feature.
- https://github.com/johnsoncodehk/volar/commit/6a87f79510971b175abecf5a9e09642b7a12e077
- https://github.com/johnsoncodehk/volar/commit/43e2d2fcae4763477ae2c0ef3168dd6d5519bf11
`volar` is now available in `vim-lsp`, so I added it to README.
DEMO (vim-lsp)
-------------------------------------------------------
https://user-images.githubusercontent.com/188642/131953744-b2ec8f04-0ee3-4d5f-be95-4b286be08719.mp4
=> doc: mention vim-lsp

packages/vue-tsc/README.md
maybe a mention to the package name should be better.
=> docs(vue-tsc): Update README.md

README.md
See https://github.com/jadestrong/lsp-volar
It also has multi server support as can be seen in https://github.com/jadestrong/lsp-volar/blob/main/lsp-volar.el (CTRL+F volar-api, volar-doc, volar-html)
=> Add emacs volar integration by jadestrong

extensions/vscode-typescript-vue-plugin/README.md, extensions/vscode-vue-language-features/README.md
Just tried to make the README files more clear and fixed some typos
=> Improvements for 'vscode-typescript-vue-plugin' and 'vscode-vue-language-features' plugins README files

extensions/vscode-vue-language-features/README.md
As encouraged in https://github.com/johnsoncodehk/volar/issues/644#issuecomment-1059143082
Sorry about larger diff, I removed all `>`s from Vetur note. Let me know if you prefer the quote to stay as is.
=> Document recursive components

packages/vue-language-service/src/languageService.ts, packages/vue-tsc/README.md, packages/vue-tsc/bin/vue-tsc.js, packages/vue-tsc/src/apis.ts, packages/vue-tsc/src/proxy.ts, packages/vue-typescript/src/typescriptRuntime.ts
=> feat: support `--watch` flag for vue-tsc

README.md
This is a very, very rough system override and is only used for navigation purposes.
I'm not familiar with this, if you found any problems or has suggestions please feel free to tell me.
=> doc: high level system overview

extensions/vscode-vue-language-features/bin/vite.js
viteBinPath on windows is different from Linux, make it can be recognize correctly on windows.
Close #1073
=> fix: can't recognize viteBinPath on Windows

packages/pug-language-service/src/pugDocument.ts, packages/source-map/src/index.ts, packages/vue-language-service/src/documentFeatures/autoInsert.ts, packages/vue-language-service/src/documentFeatures/colorPresentations.ts, packages/vue-language-service/src/documentFeatures/format.ts, packages/vue-language-service/src/documentFeatures/linkedEditingRanges.ts, packages/vue-language-service/src/languageFuatures/callHierarchy.ts, packages/vue-language-service/src/languageFuatures/definition.ts, packages/vue-language-service/src/languageFuatures/documentHighlights.ts, packages/vue-language-service/src/languageFuatures/documentLinks.ts, packages/vue-language-service/src/languageFuatures/hover.ts, packages/vue-language-service/src/languageFuatures/references.ts, packages/vue-language-service/src/languageFuatures/rename.ts, packages/vue-language-service/src/languageFuatures/renamePrepare.ts, packages/vue-language-service/src/languageFuatures/signatureHelp.ts, packages/vue-language-service/src/utils/featureWorkers.ts, packages/vue-language-service/src/vueDocuments.ts, packages/vue-language-service/src/vuePlugins/autoWrapParentheses.ts, packages/vue-language-service/src/vuePlugins/htmlPugConversions.ts, packages/vue-tsc/src/apis.ts, packages/vue-typescript/src/typescriptRuntime.ts, packages/vue-typescript/src/use/useSfcTemplateScript.ts, packages/vue-typescript/src/vueFiles.ts
Note this is a breaking API change for vue-langauge-service and vue-typescript.
I ran the npm run build script and the project builds.
=> [chore] fix maped typo

.github/workflows/test.yml, package.json, packages/vue-language-service/tests/utils/defineRename.ts, packages/vue-language-service/tests/utils/defineTypeCheck.ts, pnpm-lock.yaml, vitest.config.ts
=> chore: rewrite tests by vitest

extensions/vscode-vue-language-features/src/features/attrNameCase.ts, extensions/vscode-vue-language-features/src/features/preview.ts, extensions/vscode-vue-language-features/src/features/tagNameCase.ts, extensions/vscode-vue-language-features/src/features/tsVersion.ts, packages/typescript-language-service/src/services/completions/basic.ts, packages/typescript-language-service/src/utils/previewer.ts, packages/typescript-vue-plugin/src/index.ts, packages/vue-code-gen/src/generators/template.ts, packages/vue-code-gen/src/vue2TemplateCompiler.ts, packages/vue-language-service/src/ideFeatures/tagNameCase.ts, packages/vue-language-service/src/languageFeatures/codeLensResolve.ts, packages/vue-language-service/src/languageFeatures/completeResolve.ts, packages/vue-language-service/src/languageFeatures/documentSemanticTokens.ts, packages/vue-language-service/src/languageService.ts, packages/vue-typescript/src/utils/localTypes.ts
Thanks for your amazing work on volar ❤️
=> fix: typos

packages/vue-language-service/src/plugins/vue.ts
In thread https://github.com/johnsoncodehk/volar/issues/1219
Invited by @johnsoncodehk to submit a PR for the improved prompt message to user, to make clearer how to fix the issue of typescript intellisense being disabled on template.
=> Fix: Improve prompt on TS intellisense in template

extensions/vscode-vue-language-features/src/features/doctor.ts
When showing doctor panel check if vetur is active and display a warning.
Fixes last point of https://github.com/johnsoncodehk/volar/issues/1254
=> Check if vetur is active

extensions/vscode-vue-language-features/README.md
There seemed to be no documentation for the Aditional code.
So I linked to the most detailed sources I've seen.
If you don't like the content, feel free to edit it.
Thank you
=> add class component aditional code detail document

README.md
This is a first draft for the contribution guidelines. You can edit some stuff if you want.
=> Add Contribution Guide

packages/vue-language-server/bin/vue-language-server.js
Close #1509 
```
$ ./packages/vue-language-server/bin/vue-language-server.js --version
0.38.1
```
=> Add --version flag for vue-language-server

extensions/vscode-vue-language-features/package.json, extensions/vscode-vue-language-features/package.nls.json
provide translation for "workspaceTrust" in a package.nls.json file
fixes https://github.com/johnsoncodehk/volar/issues/1516
=> Fix workspaceTrust description

packages/vue-component-meta/src/index.ts, packages/vue-component-meta/tests/index.spec.ts, packages/vue-test-workspace/vue-component-meta/reference-type-events/my-events.ts, packages/vue-test-workspace/vue-component-meta/reference-type-props/component.vue, packages/vue-test-workspace/vue-component-meta/reference-type-props/my-props.ts
Extract nested/union properties from typescript TypeChecker
<details>
<summary><strong>Component input (with complex props)</strong></summary>
```vue
<script setup lang="ts">
export type MyComponentShapes = 'straight' | 'rounded' | 'curved'
export type MyComponentIcon = 'dot' | 'chevron' | 'plus'
export interface MyComponentNestedItem {
title: string
content: string
}
class ShapeWithIcon {
/**
* The shape of the ShapeWithIcon property.
*/
public title: string
public shape: MyComponentShapes
public actionIcon: MyComponentIcon
constructor(
title: string,
shape: MyComponentShapes,
actionIcon: MyComponentIcon
) {
this.title = title
this.shape = shape
this.actionIcon = actionIcon
}
}
enum SizeEnum {
Small,
Medium,
Large,
}
const categories = [
'Uncategorized',
'Content',
'Interaction', …
```
=> Vue meta/improve props extraction

packages/vue-typescript/src/getProgram.ts
https://github.com/johnsoncodehk/volar/issues/1647
我也遇到了同样的问题，我尝试修复了一下，没有做过多测试，如果你已经在下版本修复，请忽略
=> fix: vue-tsc --watch not work

packages/vue-component-meta/tests/index.spec.ts, packages/vue-test-workspace/vue-component-meta/reference-type-props/component-js-setup.vue, packages/vue-test-workspace/vue-component-meta/reference-type-props/component-js.vue
Increase the number of test cases 
Surfaces one issue with defaults
=> feat: add more tests for props

extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json
=> fix: correct scopes for vue-directives-control captures

extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json
=> feat: uniquely scope attribute shorthands

packages/vue-language-core/src/generators/script.ts, packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/parsers/scriptRanges.ts, packages/vue-language-core/src/plugins/vue-tsx.ts, packages/vue-language-core/src/sourceFile.ts, packages/vue-language-core/src/types.ts, packages/vue-language-core/src/utils/localTypes.ts, packages/vue-language-core/src/utils/string.ts, packages/vue-language-service/src/plugins/vue-template.ts
Reverts johnsoncodehk/volar#1898
Revert because this increases memory usage in some cases.
=> Revert "perf: reduce VueSourceFile overhead memory usage"

vue-language-tools/vue-component-meta/README.md
As per our discord [chat](https://discord.com/channels/793943652350427136/1027819645677350912) I have updated `vue-component-meta` readme according to the bast of my knowledge.
I hope you like it.
=> docs(vue-component-meta): updated README

packages/language-core/src/languageContext.ts
=> typo: shold -> should

extensions/vscode-vue-language-features/package.json, extensions/vscode-vue-language-features/syntaxes/vue.tmLanguage.json, vue-language-tools/vue-language-service/src/plugins/vue.ts
=> feat: support syntax highlighting for `lang="json5"`

packages/vue-component-meta/README.md
=> docs: update the sample code, add comma

packages/vue-component-meta/src/index.ts
=> feat(component-meta): support for functional component

packages/vue-language-core/schemas/vue-tsconfig.schema.json, packages/vue-language-core/src/generators/script.ts, packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/parsers/scriptSetupRanges.ts, packages/vue-language-core/src/plugins/file-md.ts, packages/vue-language-core/src/plugins/vue-tsx.ts, packages/vue-language-core/src/types.ts, packages/vue-language-core/src/utils/localTypes.ts, packages/vue-language-core/src/utils/ts.ts, packages/vue-test-workspace/vue-tsc/#2472/Comp.vue, packages/vue-test-workspace/vue-tsc/#2472/GenericComp.vue, packages/vue-test-workspace/vue-tsc/#2472/env.d.ts, packages/vue-test-workspace/vue-tsc/#2472/main.vue, packages/vue-test-workspace/vue-tsc/components/main.vue, packages/vue-test-workspace/vue-tsc/components/script-setup-generic.vue, packages/vue-test-workspace/vue-tsc/tsconfig.json
=> feat: Support for Vue 3.3 `defineProps()`

packages/vscode-vue/syntaxes/vue.tmLanguage.json
=> feat: support `lang="vue"`

packages/vue-language-core/src/utils/directorySharedTypes.ts
close #3268, close #3265, close #3252
Ref: microsoft/TypeScript#54630
=> fix: component type missing for TS 5.1.3

packages/vue-language-core/src/utils/transform.ts, packages/vue-test-workspace/vue-tsc/#3258/main.vue, packages/vue-test-workspace/vue-tsc/#3258/side-effect.vue
=> fix: inline variables are wrongly transformed as ctxVars

packages/vue-language-core/src/utils/directorySharedTypes.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/#3122/Comp.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/#3122/main.vue
=> fix: allow passing undefined as events

packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/utils/directorySharedTypes.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/#3171/main.vue
=> fix: allow passing inline components or without using defineComponent

packages/vue-component-meta/src/index.ts, packages/vue-language-service/tests/utils/createTester.ts, packages/vue-tsc/src/index.ts
=> fix: sync volar usage

packages/vue-language-core/src/generators/script.ts, packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/utils/globalTypes.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/#3371/main.vue
=> fix: allow slots to have no arguments

packages/vue-component-meta/src/index.ts, packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/plugins/file-html.ts, packages/vue-language-core/src/plugins/file-md.ts, packages/vue-language-core/src/plugins/vue-sfc-customblocks.ts, packages/vue-language-core/src/plugins/vue-sfc-scripts.ts, packages/vue-language-core/src/plugins/vue-sfc-styles.ts, packages/vue-language-core/src/plugins/vue-sfc-template.ts, packages/vue-language-core/src/plugins/vue-tsx.ts, packages/vue-language-core/src/sourceFile.ts, packages/vue-language-core/src/utils/parseCssClassNames.ts, packages/vue-language-core/src/utils/parseCssVars.ts, packages/vue-language-service/src/languageService.ts, packages/vue-language-service/src/plugins/vue-autoinsert-dotvalue.ts, packages/vue-language-service/src/plugins/vue-directive-comments.ts, packages/vue-language-service/src/plugins/vue-twoslash-queries.ts, packages/vue-language-service/tests/findDefinition.ts, packages/vue-language-service/tests/rename.ts, packages/vue-tsc/src/index.ts
=> perf: hoist regexp if possible

packages/vue-language-core/src/generators/script.ts, packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/utils/parseCssClassNames.ts
Resolves #3363 
Related code diffs:
1. [Deleted method which collected classes](https://github.com/vuejs/language-tools/commit/6c64b3c9a65af72a1158e327f57868bde137ff90#diff-863a52fc05b9b1216d03132ba9fb28d5bf8ec2df9a7b52c945da524becfd4db7L137-L140)
2. Not updated usages: [1](https://github.com/vuejs/language-tools/commit/6c64b3c9a65af72a1158e327f57868bde137ff90#diff-e8276945dcc5840af5e8ded7cf8cebe312e80d50e863d3e50191ec42ccd7d940R843-R846) [2](https://github.com/vuejs/language-tools/commit/6c64b3c9a65af72a1158e327f57868bde137ff90#diff-c7114f176ce3206d5d28c88b343bd665437e8184606a156d399f29fd81dd1372R174) [3](https://github.com/vuejs/language-tools/commit/6c64b3c9a65af72a1158e327f57868bde137ff90#diff-c7114f176ce3206d5d28c88b343bd665437e8184606a156d399f29fd81dd1372R692)
=> fix(class references): non scoped classes resolution regression

packages/vscode-vue/src/common.ts, pnpm-lock.yaml
Though I wonder wether we cant just update initialization options and use regular server restart like:
```ts
context.subscriptions.push(vscode.commands.registerCommand('volar.action.restartServer', async () => {
clients[0]!.clientOptions.initializationOptions = await getInitializationOptions(ServerMode.PartialSemantic, context)
clients[1]!.clientOptions.initializationOptions = await getInitializationOptions(ServerMode.Syntactic, context)
// ...
```
=> Use faster method after config change

packages/vue-language-core/src/parsers/scriptSetupRanges.ts
=> chore: fix typo

packages/vue-language-core/src/generators/script.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/#3440/main.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/components/main.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/defineProp_B/main.vue
=> fix: allow top-level await in script setup blocks with generics

packages/vue-language-core/src/utils/transform.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/events/main.vue
[playground link](https://play.vuejs.org/#eNqFUsuOm0AQ/JXWXAySFyLtzcLIeThSckiiJLdMDixuHHZhZjQP2xLi39M9eLGd5wHBdFVXF1M9iJfGZIeAYiUKV9vWeHDogymlanujrYcBLDYwQmN1DwuiLmbote7NuZ7lfGAlgmutnIdGa1hzc/IilarIJ3kSpoPH3nSVRzoBFKYchkgfxyLn0VSrWXtTWauPd01Q9VqK5JDCujzrHqQA2DByhydj0blWKyJxxdMnkydR4sJI7JyEi3yeLJbCO3LatPvs0WlFNzDwZCl4dNuh/WhYyEmxgogwVnWdPr6PNW8DLp/r9Q+sn/5Qf3QnrknxiSyiPaAUM+Yru0c/wdsvH/BE3zPY613oiP0P8DM63QX2ONFeBbUj21e86PZdDKtV+69ue/Ko+KJmo8wcI18KCo9D/NuvX+zeZ/exT6qRbvE5+F9XCLpK7SkRTzKltJQ7PdNqYN96R8HssGkVbvlUDAwDxMTfUogr+KZC/4D2+3JCONntHPUFZnQsk5Tfly07z7vatChCm/UQvNcKNnXX1k/kL5pJFvPgxRLeUEOm9DFJU/I+I0U+9f5X69bqb4K38I3q9YKOPwGNCjoa)
The function expression should be typed correctly as same as arrow function.
=> feat: support function expression emit event

packages/vue-language-core/src/types.ts, packages/vue-language-core/src/utils/ts.ts
=> feat: support nested plugins

packages/vue-language-core/src/generators/template.ts, packages/vue-language-service/src/languageService.ts
=> fix: replace `@ts-expect-error` with `@vue-expect-error`

packages/vue-language-core/src/generators/script.ts
See https://github.com/vuejs/language-tools/pull/3550#issuecomment-1729036431
=> fix: don't import alias macros

packages/vue-test-workspace/vue-tsc/non-strict-template/#1855/Comp.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/#1855/main.vue
close #1855
This issue should be fixed by https://github.com/vuejs/language-tools/commit/6df0db7472db0f8fcb8da22dd68ea584768118aa and https://github.com/vuejs/language-tools/pull/3585
=> test: add test for #1855

packages/vue-language-core/src/generators/script.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/components/main.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/components/script-setup-generic.vue, packages/vue-test-workspace/vue-tsc/non-strict-template/type-helpers/main.vue, packages/vue-tsc/tests/__snapshots__/dts.spec.ts.snap
=> fix: accurate exposed type with refs in generic component

README.md
Information about Eclipse integration ;)
=> Information about Eclipse integration

packages/vue-language-core/src/generators/script.ts, packages/vue-language-core/src/parsers/scriptSetupRanges.ts, packages/vue-test-workspace/vue-tsc/non-strict-template/#3637/main.vue, packages/vue-tsc/tests/__snapshots__/dts.spec.ts.snap
=> fix: regression with `defineExpose`

packages/vue-language-core/src/generators/template.ts, packages/vue-language-core/src/utils/transform.ts, packages/vue-test-workspace/complete/#3658/input/entry.vue, packages/vue-test-workspace/complete/#3658/output/entry.vue
=> fix: add autocomplete for v-slot parameters

packages/language-core/src/generators/script.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap
fix https://github.com/vuejs/repl/actions/runs/6656548610/job/18089340458
=> fix: add missing `__VLS_Prettify` type for `withDefaults()`

packages/language-core/src/plugins/file-vue.ts
=> fix: incremental insertion incorrect if input at block start

packages/language-service/src/plugins/vue-extract-file.ts
=> fix: avoid reading undefined properties in non-vscode editors

packages/component-meta/README.md
- replace createComponentMetaChecker with createChecker 
- replace src with lib
=> doc(component-meta): update demo

packages/language-core/lib/virtualFile/computedMappings.ts, packages/language-service/lib/plugins/vue-sfc.ts
=> fix: allow folding root elements

extensions/vscode/src/features/doctor.ts
Refs https://github.com/vuejs/language-tools/issues/3942#issuecomment-1980072720
=> chore(vscode): add `styled-components.vscode-styled-components` to the conflict list

packages/language-core/lib/codegen/script/index.ts, packages/language-core/lib/codegen/script/template.ts, packages/language-core/lib/codegen/template/context.ts, packages/language-core/lib/codegen/template/element.ts, packages/language-core/lib/codegen/template/index.ts, packages/language-core/lib/plugins/vue-tsx.ts, packages/language-core/lib/types.ts, packages/language-service/index.ts, packages/language-service/lib/plugins/vue-document-links.ts
=> feat(language-service): re-support scoped class links in template

packages/language-core/lib/codegen/script/template.ts, packages/language-core/lib/parsers/scriptSetupRanges.ts, test-workspace/tsc/vue3/defineOptions/child.vue
=> feat(language-core): support defineOptions

packages/language-core/lib/codegen/template/vFor.ts
fix #4409 
Upstream PR: https://github.com/vuejs/core/pull/11011
=> fix(language-core): `ForIteratorExpression`'s `returns` property may be undefined

packages/language-core/lib/codegen/template/element.ts
=> fix(language-core): ignore type error for new functional component

packages/language-core/lib/codegen/script/internalComponent.ts
=> fix(language-core): use type infer instead of await import

extensions/vscode/src/common.ts
https://github.com/vuejs/language-tools/pull/4206#issuecomment-2212537184
=> fix(vscode): add vue vine to hybrid mode compatible list

test-workspace/tsc/#4503/globalcomp.vue, test-workspace/tsc/#4503/globals.d.ts, test-workspace/tsc/#4503/main.vue, test-workspace/tsc/#4503/tsconfig.json
Add test case for https://github.com/vuejs/language-tools/wiki/Global-Component-Types
=> test: global components prop validation

packages/language-service/lib/plugins/data.ts, packages/language-service/lib/plugins/vue-template.ts
=> fix(language-service): completion documentations for binding attributes

packages/language-service/lib/plugins/vue-template.ts
=> fix(language-service): avoid converting internal id of special tags

packages/language-service/lib/plugins/vue-template.ts, test-workspace/language-service/complete/#4639/input/entry.vue, test-workspace/language-service/complete/#4639/output/entry.vue
=> fix(language-service): reinstate the completion for modifiers

extensions/vscode/package.json
=> fix(vscode): type of `vue.server.hybridMode` config

packages/language-core/lib/codegen/globalTypes.ts
=> fix(language-core): disable lib check on global types file

packages/language-core/lib/codegen/script/index.ts, packages/language-core/lib/codegen/script/scriptSetup.ts, packages/language-core/lib/codegen/script/styleModulesType.ts, packages/language-core/lib/codegen/script/template.ts, packages/language-core/lib/codegen/template/styleModules.ts, packages/language-server/tests/renaming.spec.ts, test-workspace/tsc/passedFixtures/vue3.5/templateRef_native/main.vue, test-workspace/tsc/passedFixtures/vue3/#4788/main.vue
=> fix(language-core): generate `__VLS_StyleModules` after template

packages/language-core/lib/virtualFile/computedSfc.ts
=> fix(language-core): hold prev track id correctly

extensions/vscode/package.json, packages/language-core/lib/parsers/scriptSetupRanges.ts, packages/typescript-plugin/index.ts, packages/typescript-plugin/lib/server.ts, packages/typescript-plugin/lib/utils.ts, pnpm-lock.yaml, tsslint.config.ts
The TSSLint config has now been moved to a separate repo: https://github.com/johnsoncodehk/tsslint-config
=> lint: use `@johnsoncodehk/tsslint-config`

extensions/vscode/src/compatibility.ts
=> fix(vscode): add `GitHub.copilot-chat` to hybrid mode compatible list

packages/language-core/lib/codegen/template/index.ts, test-workspace/tsc/passedFixtures/#5111/main.vue, test-workspace/tsc/passedFixtures/#5111/tsconfig.json, test-workspace/tsc/passedFixtures/vue3/#5111/main.vue
=> fix(language-core): intersect local `$attrs` with `__VLS_ctx.$attrs`

packages/language-plugin-pug/index.ts, test-workspace/tsc/passedFixtures/pug/#5099.vue
=> fix(language-plugin-pug): ignore duplicate attribute error of `class`

packages/language-core/lib/codegen/script/scriptSetup.ts, packages/language-core/lib/codegen/template/context.ts, packages/language-core/lib/codegen/template/index.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap
=> fix(language-core): use trick to avoid `TS4081` error on slots

packages/language-core/lib/codegen/template/context.ts, packages/language-core/lib/codegen/template/element.ts, packages/language-core/lib/codegen/template/index.ts, packages/language-core/lib/codegen/template/slotOutlet.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap
=> fix(language-core): hoist the variables that may cause `TS4081`

packages/component-meta/tests/index.spec.ts, packages/language-core/lib/codegen/script/scriptSetup.ts, packages/language-core/lib/codegen/template/elementProps.ts, packages/language-core/lib/parsers/scriptSetupRanges.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap, test-workspace/component-meta/reference-type-model/component.vue
=> feat(language-core): infer prop JSDoc from `defineModel`'s leading comments

packages/language-core/lib/codegen/script/scriptSetup.ts, packages/language-core/lib/codegen/template/element.ts, packages/language-core/lib/codegen/template/elementDirectives.ts, packages/language-core/lib/codegen/template/elementEvents.ts, packages/language-core/lib/codegen/template/elementProps.ts, packages/language-core/lib/codegen/template/objectProperty.ts, packages/language-core/lib/codegen/template/propertyAccess.ts, packages/language-core/lib/codegen/utils/camelized.ts, packages/language-core/lib/codegen/utils/index.ts, packages/language-core/lib/parsers/scriptSetupRanges.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap, test-workspace/tsc/passedFixtures/vue3/defineModel/main.vue, test-workspace/tsc/passedFixtures/vue3/defineModel/script-setup.vue
=> fix(language-core): generate camelized prop name for `defineModel`

packages/language-service/index.ts, packages/typescript-plugin/lib/common.ts
=> feat(typescript-plugin): skip declaration files in goto components definition

.gitignore, package.json, packages/language-core/lib/plugins/file-md.ts
=> fix(language-core): ignore frontmatter block in markdown files

packages/language-core/lib/parsers/scriptSetupRanges.ts
=> fix(language-core): hoist export declarations from generic script block

extensions/vscode/src/languageClient.ts, extensions/vscode/src/nodeClientMain.ts, packages/language-server/lib/types.ts, packages/language-server/node.ts
=> feat(language-server): notification-based tsserver request forwarding

packages/language-core/lib/codegen/template/elementEvents.ts, test-workspace/tsc/passedFixtures/vue3/#5428/main.vue
=> fix(language-core): do not generate redundant function scopes to affect type narrowing

extensions/vscode/package.json
=> feat(vscode): add support for `typescript.sortImports`, `typescript.removeUnusedImports` commands

extensions/vscode/index.ts
Fix compatibility with https://github.com/zardoy/typescript-vscode-plugins, refs: #4709.
=> fix(vscode): make sure tsserver loads `@vue/typescript-plugin` last

packages/component-meta/lib/base.ts, packages/language-core/lib/codegen/script/index.ts, packages/language-core/lib/types.ts, packages/language-core/lib/utils/ts.ts, packages/language-service/lib/plugins/vue-global-types-error.ts, packages/tsc/index.ts, packages/tsc/tests/dts.spec.ts, packages/typescript-plugin/index.ts
=> fix(language-core): find `node_modules` based on file's directory

packages/language-core/lib/codegen/script/component.ts, packages/language-core/lib/codegen/script/template.ts, packages/language-core/lib/codegen/utils/merge.ts, packages/tsc/tests/__snapshots__/dts.spec.ts.snap, test-workspace/tsc/passedFixtures/vue3.4/components/main.vue, test-workspace/tsc/passedFixtures/vue3.4/defineModel/main.vue, test-workspace/tsc/passedFixtures/vue3/components/main.vue, test-workspace/tsc/passedFixtures/vue3/defineModel/main.vue
=> fix(language-core): do not spread exposed object

packages/language-core/lib/plugins/vue-tsx.ts, packages/language-server/index.ts, packages/language-service/lib/plugins/vue-template.ts, packages/typescript-plugin/index.ts, packages/typescript-plugin/lib/requests/getComponentSlots.ts, packages/typescript-plugin/lib/requests/index.ts
https://github.com/user-attachments/assets/3791b5bc-8041-4bf7-a4f2-8a20e2c11183
=> feat(language-service): native completion experience for slot names

packages/language-core/lib/codegen/codeFeatures.ts, packages/language-core/lib/codegen/template/element.ts, packages/language-core/lib/codegen/template/slotOutlet.ts, packages/language-core/lib/utils/shared.ts, packages/language-service/lib/plugins/vue-document-highlights.ts
=> fix(language-service): skip document highlight from tsserver within element tags

extensions/vscode/lib/reactivityVisualization.ts
=> fix(vscode): flatten reactivity visualization decorators

packages/typescript-plugin/lib/requests/getReactiveReferences.ts
Fixed the issue where reactivity visualization could not be obtained at `triple` in the following cases.
```ts
const count = ref(0)
const double = computed(() => count.value * 2)
const triple = computed(() => double.value)
```
=> fix(typescript-plugin): ensure TS node corresponds to the mapping range

packages/language-core/lib/codegen/template/templateChild.ts
=> fix(language-core): exclude effect of comments on root node
